using System;
using System.Collections.Generic;

namespace WinPanel
{
    // French UI table for Loc: keys are the exact English source strings.
    public static class LangFr
    {
        public static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { " and more...", " et plus..." },
            { " at (", " à (" },
            { " items?", " éléments ?" },
            { "\". Use Ctrl/Alt/Shift/Win + a letter or digit, e.g. Ctrl+Alt+P (or None).", "\". Format : Ctrl/Alt/Shift/Win + lettre ou chiffre, ex. Ctrl+Alt+P (ou None)." },
            { "(empty)", "(vide)" },
            { "(no other tabs)", "(aucun autre onglet)" },
            { "+ Save", "+ Enregistrer" },
            { "Add Tab", "Ajouter un onglet" },
            { "Add bookmark group", "Ajouter un groupe de favoris" },
            { "Add command", "Ajouter une commande" },
            { "Add command...", "Ajouter une commande..." },
            { "Add current folder", "Ajouter le dossier courant" },
            { "Add current folder to bookmarks", "Ajouter le dossier courant aux favoris" },
            { "Add folder bookmark", "Ajouter un favori dossier" },
            { "Add group...", "Ajouter un groupe..." },
            { "Add to bookmarks", "Ajouter aux favoris" },
            { "Add type...", "Ajouter un type..." },
            { "After autostart - go to tray", "Après le démarrage auto - dans la zone de notification" },
            { "All", "Tout" },
            { "Allow adding icons", "Autoriser l'ajout d'icônes" },
            { "Always keep tray icon", "Toujours garder l'icône de notification" },
            { "An error occurred but Tilettes keeps running.", "Une erreur s'est produite mais Tilettes continue de fonctionner." },
            { "Apps (system)", "Applications (système)" },
            { "Autostart & window", "Démarrage auto & fenêtre" },
            { "Autostart with Windows", "Lancer avec Windows" },
            { "BOOKMARKS", "FAVORIS" },
            { "Backup created:", "Sauvegarde créée :" },
            { "Backup every N days (0 = off):", "Sauvegarde tous les N jours (0 = off) :" },
            { "Backup failed - see log.txt", "Échec de la sauvegarde - voir log.txt" },
            { "Backup now", "Sauvegarder maintenant" },
            { "Backup saved: ", "Sauvegarde enregistrée : " },
            { "Bookmark name:", "Nom du favori :" },
            { "Bookmarks", "Favoris" },
            { "Calculator", "Calculatrice" },
            { "Cancel", "Annuler" },
            { "Cannot parse the hotkey \"", "Raccourci illisible : \"" },
            { "Cannot read the archive: ", "Impossible de lire l'archive : " },
            { "Capture Start button (Win)", "Capturer la touche Démarrer (Win)" },
            { "Change Icon", "Changer l'icône" },
            { "Change...", "Modifier..." },
            { "Check every N days:", "Vérifier tous les N jours :" },
            { "Check for updates automatically", "Rechercher les mises à jour automatiquement" },
            { "Check now", "Vérifier maintenant" },
            { "Clear", "Effacer" },
            { "Clear history", "Effacer l'historique" },
            { "Clear selection", "Effacer la sélection" },
            { "Click an address to copy it", "Cliquez sur une adresse pour la copier" },
            { "Click to copy the address", "Cliquez pour copier l'adresse" },
            { "Close", "Fermer" },
            { "Close & create example tiles", "Fermer & créer des tuiles d'exemple" },
            { "Command:", "Commande :" },
            { "Console", "Console" },
            { "Copied ✓", "Copié ✓" },
            { "Copy folder path", "Copier le chemin du dossier" },
            { "Copy path", "Copier le chemin" },
            { "Could not reach GitHub Releases - check the internet connection.", "Impossible de joindre GitHub Releases - vérifiez la connexion Internet." },
            { "Ctrl+Click a folder opens Mini Explorer", "Ctrl+clic sur un dossier ouvre le mini-explorateur" },
            { "Ctrl+L or Edit - edit path · F5 - refresh · Backspace - up · Enter - open · double-click - open", "Ctrl+L ou Modifier - modifier le chemin · F5 - actualiser · Retour arrière - remonter · Entrée - ouvrir · double-clic - ouvrir" },
            { "Ctrl+mouse wheel - console font size", "Ctrl+molette - taille de police de la console" },
            { "Current window: ", "Fenêtre actuelle : " },
            { "D", "D" },
            { "Def. Item Size:", "Taille déf. des tuiles :" },
            { "Desc", "Descri" },
            { "Description", "Description" },
            { "Description text", "Texte de description" },
            { "Description...", "Description..." },
            { "Descriptions", "Descriptions" },
            { "Details in log.txt", "Détails dans log.txt" },
            { "Drag to resize the console", "Faites glisser pour redimensionner la console" },
            { "Edit", "Modifier" },
            { "Edit command", "Modifier la commande" },
            { "Edit command...", "Modifier la commande..." },
            { "Exact", "Exact" },
            { "Exit", "Quitter" },
            { "Expects a .zip created by \"Backup now\" / scheduled backup; files are unpacked into the working folder, Tilettes.exe is not replaced", "Attend un .zip créé par \"Sauvegarder maintenant\" / la sauvegarde planifiée ; les fichiers sont décompressés dans le dossier de travail, Tilettes.exe n'est pas remplacé" },
            { "Explorer", "Explorateur" },
            { "Export...", "Exporter..." },
            { "Extract failed: ", "Échec de l'extraction : " },
            { "Extract here (tar)", "Extraire ici (tar)" },
            { "File Type Icons", "Icônes par type de fichier" },
            { "File manager", "Gestionnaire de fichiers" },
            { "File types:", "Types de fichiers :" },
            { "Folder", "Dossier" },
            { "Found a bug or have an idea? Create an issue on GitHub:", "Un bug ou une idée ? Créez une issue sur GitHub :" },
            { "Full backup (settings + shortcuts + bookmarks) into autoBackup\\; runs 3 minutes after launch when due", "Sauvegarde complète (réglages + raccourcis + favoris) dans autoBackup\\ ; lancée 3 minutes après le démarrage quand due" },
            { "Fuzzy accuracy (0-3):", "Précision floue (0-3) :" },
            { "Grid Columns:", "Colonnes de la grille :" },
            { "Grid Rows:", "Lignes de la grille :" },
            { "Grid Transp. (0-255):", "Transp. grille (0-255) :" },
            { "Grid:", "Grille :" },
            { "Group (empty = top level):", "Groupe (vide = premier niveau) :" },
            { "Group name:", "Nom du groupe :" },
            { "Icon Scale (%):", "Échelle des icônes (%) :" },
            { "Icons by type...", "Icônes par type..." },
            { "Import...", "Importer..." },
            { "Install updates automatically", "Installer les mises à jour automatiquement" },
            { "Just drag a shortcut or a file onto the panel - it becomes a tile.", "Glissez simplement un raccourci ou un fichier sur le panneau - il devient une tuile." },
            { "Language:", "Langue :" },
            { "Light", "Clair" },
            { "Light Theme", "Thème clair" },
            { "Like Tilettes? Support the author with crypto:", "Vous aimez Tilettes ? Soutenez l'auteur en crypto :" },
            { "M", "M" },
            { "Maintenance & Start Menu", "Maintenance & Menu Démarrer" },
            { "Match precision: exact or fuzzy (0-3)", "Précision de correspondance : exacte ou floue (0-3)" },
            { "Meta", "Méta" },
            { "Metadata", "Métadonnées" },
            { "Minimize instead of close", "Réduire au lieu de fermer" },
            { "More", "Plus" },
            { "Move down", "Descendre" },
            { "Move out of folder", "Sortir du dossier" },
            { "Move to tab", "Déplacer vers l'onglet" },
            { "Move up", "Monter" },
            { "New Name", "Nouveau nom" },
            { "New Tab Name", "Nom du nouvel onglet" },
            { "New name:", "Nouveau nom :" },
            { "New version available: ", "Nouvelle version disponible : " },
            { "New version available: v", "Nouvelle version disponible : v" },
            { "New window", "Nouvelle fenêtre" },
            { "None (dark)", "Aucun (sombre)" },
            { "Notepad", "Bloc-notes" },
            { "Nothing was restored - see log.txt", "Rien n'a été restauré - voir log.txt" },
            { "OK", "OK" },
            { "Open", "Ouvrir" },
            { "Open With by File Type", "Ouvrir avec par type de fichier" },
            { "Open console window here", "Ouvrir une fenêtre console ici" },
            { "Open containing folder", "Ouvrir le dossier parent" },
            { "Open folders in:", "Ouvrir les dossiers dans :" },
            { "Open in Explorer", "Ouvrir dans l'Explorateur" },
            { "Open in Mini Explorer", "Ouvrir dans le mini-explorateur" },
            { "Open standard", "Ouvrir (standard)" },
            { "Open the donate section on GitHub", "Ouvrir la section dons sur GitHub" },
            { "Open with by type...", "Ouvrir avec par type..." },
            { "Paths", "Chemins" },
            { "Popup window", "Fenêtre contextuelle" },
            { "Pressing the Win key shows the panel instead of the Start menu", "La touche Win affiche le panneau au lieu du menu Démarrer" },
            { "Refresh", "Actualiser" },
            { "Remember active tab", "Mémoriser l'onglet actif" },
            { "Remove", "Supprimer" },
            { "Remove ", "Supprimer " },
            { "Remove from Panel", "Retirer du panneau" },
            { "Remove icon", "Retirer l'icône" },
            { "Remove selected", "Supprimer la sélection" },
            { "Remove selected (", "Supprimer la sélection (" },
            { "Rename", "Renommer" },
            { "Rename bookmark", "Renommer le favori" },
            { "Rename...", "Renommer..." },
            { "Restart", "Redémarrer" },
            { "Restore", "Afficher" },
            { "Restore archive...", "Restaurer l'archive..." },
            { "Restore backup", "Restaurer la sauvegarde" },
            { "Restore failed: ", "Échec de la restauration : " },
            { "Restore from a backup archive", "Restaurer depuis une archive de sauvegarde" },
            { "Return from a folder after this many seconds without activity (0 = off)", "Sortir d'un dossier après autant de secondes sans activité (0 = off)" },
            { "Run", "Exécuter" },
            { "Same window", "Même fenêtre" },
            { "Save", "Enregistrer" },
            { "Save backup", "Enregistrer la sauvegarde" },
            { "Save backup (zip)", "Enregistrer la sauvegarde (zip)" },
            { "Save failed: ", "Échec de l'enregistrement : " },
            { "Save search history", "Enregistrer l'historique de recherche" },
            { "Search", "Rechercher" },
            { "Search files (fuzzy, any keyboard layout)", "Rechercher des fichiers (flou, toute disposition clavier)" },
            { "Search fonts:", "Polices de recherche :" },
            { "Search history cleared.", "Historique de recherche effacé." },
            { "Search in descriptions", "Rechercher dans les descriptions" },
            { "Search in exe name, product, company", "Rechercher dans le nom exe, produit, société" },
            { "Search in full paths", "Rechercher dans les chemins complets" },
            { "Search in item descriptions", "Rechercher dans les descriptions des éléments" },
            { "Search in metadata (exe, product)", "Rechercher dans les métadonnées (exe, produit)" },
            { "Search in the Start Menu tab", "Rechercher dans l'onglet Menu Démarrer" },
            { "Search scope: click switches folder / everywhere", "Portée : un clic bascule dossier / partout" },
            { "Search...", "Rechercher..." },
            { "Settings", "Paramètres" },
            { "Show / hide bookmarks panel", "Afficher / masquer le volet des favoris" },
            { "Show / hide top bookmarks bar", "Afficher / masquer la barre de favoris supérieure" },
            { "Show in Explorer", "Afficher dans l'Explorateur" },
            { "Show the welcome window again", "Réafficher la fenêtre de bienvenue" },
            { "Show window hotkey:", "Raccourci d'affichage :" },
            { "Simple text editor", "Éditeur de texte simple" },
            { "Size", "Taille" },
            { "Size-1", "1 x 1" },
            { "Skin & theme:", "Habillage & thème :" },
            { "Start", "Démarrer" },
            { "Start Menu", "Menu Démarrer" },
            { "Start Menu (all users)", "Menu Démarrer (tous les utilisateurs)" },
            { "Start Menu (local)", "Menu Démarrer (local)" },
            { "Start Menu (user)", "Menu Démarrer (utilisateur)" },
            { "Start Menu sync failed - see log.txt", "Échec de la synchro du Menu Démarrer - voir log.txt" },
            { "Start Menu synced:", "Menu Démarrer synchronisé :" },
            { "Startup Size:", "Taille au démarrage :" },
            { "Support section on GitHub (README)", "Section de soutien sur GitHub (README)" },
            { "Support the author", "Soutenir l'auteur" },
            { "Sync Start Menu every N h (0 = off):", "Synchro Menu Démarrer toutes les N h (0 = off) :" },
            { "Sync Start Menu now", "Synchroniser le Menu Démarrer" },
            { "Tabs Font:", "Police des onglets :" },
            { "Thanks for trying Tilettes!", "Merci d'essayer Tilettes !" },
            { "The app periodically asks GitHub Releases for a newer version (no auto-download yet)", "L'application interroge périodiquement GitHub Releases pour une version plus récente (pas encore de téléchargement auto)" },
            { "The description is used by the search and pops up as a tooltip when hovering the element.", "La description est utilisée par la recherche et apparaît en infobulle au survol de l'élément." },
            { "This archive has no settings.ini / records.xml - it is not a Tilettes backup.", "Cette archive ne contient pas settings.ini / records.xml - ce n'est pas une sauvegarde Tilettes." },
            { "This is a beta version - bugs and rough edges are possible.", "Ceci est une version bêta - des bugs et des imperfections sont possibles." },
            { "Tiles Font:", "Police des tuiles :" },
            { "Tilettes", "Tilettes" },
            { "Tilettes backup archives (*.zip)|*.zip|All files (*.*)|*.*", "Archives de sauvegarde Tilettes (*.zip)|*.zip|Tous les fichiers (*.*)|*.*" },
            { "Tilettes console · ", "Console Tilettes · " },
            { "Tilettes rules (*.xml)|*.xml|All files (*.*)|*.*", "Règles Tilettes (*.xml)|*.xml|Tous les fichiers (*.*)|*.*" },
            { "UI Font:", "Police de l'interface :" },
            { "Update", "Mettre à jour" },
            { "Updates", "Mises à jour" },
            { "Version ", "Version " },
            { "Wallet addresses and other ways to help live on GitHub:", "Les adresses de portefeuilles et d'autres moyens d'aider sont sur GitHub :" },
            { "Window Position:", "Position de la fenêtre :" },
            { "Windows calculator", "Calculatrice Windows" },
            { "You are on the latest version: v", "Vous êtes sur la dernière version : v" },
            { "[console process exited - press Restart]", "[processus console terminé - appuyez sur Redémarrer]" },
            { "\nThe green Update plate has appeared in the corner.", "\nLa pastille verte « Mettre à jour » est apparue dans le coin." },
            { "address copied to clipboard", "adresse copiée dans le presse-papiers" },
            { "box", "champ" },
            { "columns x", "colonnes x" },
            { "results", "résultats" },
            { "rows", "lignes" },
            { "sec idle", "s d'inactivité" },
            { "text", "texte" },
            { "♥ Donate", "♥ Faire un don" }
        };
    }
}
