using System;
using System.Collections.Generic;

namespace WinPanel
{
    // Simplified Chinese UI table for Loc: keys are the exact English source strings.
    public static class LangZh
    {
        public static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { " and more...", " 及更多..." },
            { " at (", " 位置 (" },
            { " items?", " 项？" },
            { "\". Use Ctrl/Alt/Shift/Win + a letter or digit, e.g. Ctrl+Alt+P (or None).", "\"。格式：Ctrl/Alt/Shift/Win + 字母或数字，例如 Ctrl+Alt+P（或 None）。" },
            { "(empty)", "（空）" },
            { "(no other tabs)", "（没有其他标签页）" },
            { "+ Save", "+ 保存" },
            { "Add Tab", "添加标签页" },
            { "Add bookmark group", "添加书签分组" },
            { "Add command", "添加命令" },
            { "Add command...", "添加命令..." },
            { "Add current folder", "添加当前文件夹" },
            { "Add current folder to bookmarks", "将当前文件夹加入书签" },
            { "Add folder bookmark", "添加文件夹书签" },
            { "Add group...", "添加分组..." },
            { "Add to bookmarks", "加入书签" },
            { "Add type...", "添加类型..." },
            { "After autostart - go to tray", "自启动后 - 进入托盘" },
            { "All", "全部" },
            { "Allow adding icons", "允许添加图标" },
            { "Always keep tray icon", "始终保留托盘图标" },
            { "An error occurred but Tilettes keeps running.", "发生错误，但 Tilettes 仍在运行。" },
            { "Apps (system)", "应用（系统）" },
            { "Autostart & tray", "自启动与托盘" },
            { "Autostart with Windows", "随 Windows 自启动" },
            { "BOOKMARKS", "书签" },
            { "Backup created:", "已创建备份：" },
            { "Backup every N days (0 = off):", "每 N 天备份一次（0 = 关）：" },
            { "Backup failed - see log.txt", "备份失败 - 见 log.txt" },
            { "Backup now", "立即备份" },
            { "Backup saved: ", "备份已保存：" },
            { "Bookmark name:", "书签名称：" },
            { "Bookmarks", "书签" },
            { "Calculator", "计算器" },
            { "Cancel", "取消" },
            { "Cannot parse the hotkey \"", "无法解析快捷键 \"" },
            { "Cannot read the archive: ", "无法读取压缩包：" },
            { "Capture the Win key", "捕获 Win 键" },
            { "Capture Start button click", "捕获开始按钮的单击" },
            { "Open tiles:", "打开磁贴:" },
            { "Open results:", "打开搜索结果:" },
            { "Single click", "单击" },
            { "Double click", "双击" },
            { "How tiles open: a single click launches right away, a double click needs two clicks", "磁贴打开方式：单击立即打开，双击需要点两次" },
            { "How search results open: by a single click or a double click", "搜索结果的打开方式：单击或双击" },
            { "A left click on the Start button (screen corner) opens the panel instead of the Start menu", "左键单击开始按钮（屏幕角落）打开面板而不是开始菜单" },
            { "Open Start menu", "打开开始菜单" },
            { "Window", "窗口" },
            { "Tile labels", "磁贴标签" },
            { "Folders", "文件夹" },
            { "Panel & hotkeys", "面板与快捷键" },
            { "Fonts", "字体" },
            { "File types & explorer", "文件类型与资源管理器" },
            { "Open folders with:", "用以下程序打开文件夹:" },
            { "Change Icon", "更改图标" },
            { "Change...", "更改..." },
            { "Check every N days:", "每 N 天检查一次：" },
            { "Check for updates automatically", "自动检查更新" },
            { "Check now", "立即检查" },
            { "Clear", "清空" },
            { "Clear history", "清除历史" },
            { "Clear selection", "清除选择" },
            { "Close", "关闭" },
            { "Close & create example tiles", "关闭并创建示例磁贴" },
            { "Command:", "命令：" },
            { "Console", "控制台" },
            { "Copy folder path", "复制文件夹路径" },
            { "Copy path", "复制路径" },
            { "Could not reach GitHub Releases - check the internet connection.", "无法连接 GitHub Releases - 请检查网络连接。" },
            { "Ctrl+Click a folder opens Mini Explorer", "Ctrl+点击文件夹打开迷你资源管理器" },
            { "Ctrl+L or Edit - edit path · F5 - refresh · Backspace - up · Enter - open · double-click - open", "Ctrl+L 或 编辑 - 编辑路径 · F5 - 刷新 · 退格 - 上级 · 回车 - 打开 · 双击 - 打开" },
            { "Ctrl+mouse wheel - console font size", "Ctrl+滚轮 - 控制台字号" },
            { "Current window: ", "当前窗口：" },
            { "D", "描" },
            { "Def. Item Size:", "默认磁贴大小：" },
            { "Desc", "描述" },
            { "Description", "描述" },
            { "Description text", "描述文本" },
            { "Description...", "描述..." },
            { "Descriptions", "描述" },
            { "Details in log.txt", "详情见 log.txt" },
            { "Drag to resize the console", "拖动以调整控制台大小" },
            { "Edit", "编辑" },
            { "Edit command", "编辑命令" },
            { "Edit command...", "编辑命令..." },
            { "Exact", "精确" },
            { "Exit", "退出" },
            { "Expects a .zip created by \"Backup now\" / scheduled backup; files are unpacked into the working folder, Tilettes.exe is not replaced", "需要由 \"立即备份\" / 计划备份创建的 .zip；文件解压到工作文件夹，不替换 Tilettes.exe" },
            { "Explorer", "资源管理器" },
            { "Export...", "导出..." },
            { "Extract failed: ", "解压失败：" },
            { "Extract here (tar)", "解压到此处（tar）" },
            { "File Type Icons", "按文件类型的图标" },
            { "File manager", "文件管理器" },
            { "File types:", "文件类型：" },
            { "Folder", "文件夹" },
            { "Found a bug or have an idea? Create an issue on GitHub:", "发现错误或有建议？在 GitHub 创建 issue：" },
            { "Full backup (settings + shortcuts + bookmarks) into autoBackup\\; runs 3 minutes after launch when due", "完整备份（设置 + 快捷方式 + 书签）到 autoBackup\\；到期时在启动 3 分钟后执行" },
            { "Fuzzy accuracy (0-3):", "模糊精度 (0-3)：" },
            { "Grid Columns:", "网格列数：" },
            { "Grid Rows:", "网格行数：" },
            { "Grid Transp. (0-255):", "网格透明度 (0-255)：" },
            { "Grid:", "网格：" },
            { "Group (empty = top level):", "分组（空 = 顶层）：" },
            { "Group name:", "分组名称：" },
            { "Icon Scale (%):", "图标缩放 (%)：" },
            { "Icons by type...", "按类型设置图标..." },
            { "Import...", "导入..." },
            { "Install updates automatically", "自动安装更新" },
            { "Just drag a shortcut or a file onto the panel - it becomes a tile.", "只需把快捷方式或文件拖到面板上 - 就会变成磁贴。" },
            { "Language:", "语言：" },
            { "Light", "浅色" },
            { "Light Theme", "浅色主题" },
            { "M", "元" },
            { "Maintenance & Start Menu", "维护与开始菜单" },
            { "Match precision: exact or fuzzy (0-3)", "匹配精度：精确或模糊 (0-3)" },
            { "Meta", "元" },
            { "Metadata", "元数据" },
            { "Minimize instead of close", "最小化而不是关闭" },
            { "More", "更多" },
            { "Move down", "下移" },
            { "Move out of folder", "移出文件夹" },
            { "Move to tab", "移动到标签页" },
            { "Move up", "上移" },
            { "New Name", "新名称" },
            { "New Tab Name", "新标签页名称" },
            { "New name:", "新名称：" },
            { "New version available: ", "有新版本：" },
            { "New version available: v", "有新版本：v" },
            { "New window", "新窗口" },
            { "None (dark)", "无（深色）" },
            { "Notepad", "记事本" },
            { "Nothing was restored - see log.txt", "未恢复任何内容 - 见 log.txt" },
            { "OK", "确定" },
            { "Open", "打开" },
            { "Open With by File Type", "按文件类型选择打开方式" },
            { "Open console window here", "在此打开控制台窗口" },
            { "Open containing folder", "打开所在文件夹" },
            { "Open folders in:", "文件夹打开方式：" },
            { "Open in Explorer", "在资源管理器中打开" },
            { "Open in Mini Explorer", "在迷你资源管理器中打开" },
            { "Open standard", "默认方式打开" },
            { "Open with by type...", "按类型设置打开方式..." },
            { "Paths", "路径" },
            { "Popup window", "弹出窗口" },
            { "Pressing the Win key opens the panel instead of the Start menu", "按下 Win 键打开面板而不是开始菜单" },
            { "Refresh", "刷新" },
            { "Remember active tab", "记住活动标签页" },
            { "Remove", "移除" },
            { "Remove ", "移除 " },
            { "Remove from Panel", "从面板移除" },
            { "Remove icon", "移除图标" },
            { "Remove selected", "移除所选" },
            { "Remove selected (", "移除所选 (" },
            { "Rename", "重命名" },
            { "Rename bookmark", "重命名书签" },
            { "Rename...", "重命名..." },
            { "Restart", "重启" },
            { "Restore", "显示" },
            { "Restore archive...", "从压缩包恢复..." },
            { "Restore backup", "恢复备份" },
            { "Restore failed: ", "恢复失败：" },
            { "Restore from a backup archive", "从备份压缩包恢复" },
            { "Return from a folder after this many seconds without activity (0 = off)", "在文件夹内无操作这么多秒后返回（0 = 关）" },
            { "Run", "执行" },
            { "Same window", "同一窗口" },
            { "Save", "保存" },
            { "Save backup", "保存备份" },
            { "Save backup (zip)", "保存备份 (zip)" },
            { "Save failed: ", "保存失败：" },
            { "Save search history", "保存搜索历史" },
            { "Search", "搜索" },
            { "Search files (fuzzy, any keyboard layout)", "搜索文件（模糊，任意键盘布局）" },
            { "Search fonts:", "搜索字体：" },
            { "Search history cleared.", "搜索历史已清除。" },
            { "Search in descriptions", "在描述中搜索" },
            { "Search in exe name, product, company", "在 exe 名称、产品、公司中搜索" },
            { "Search in full paths", "在完整路径中搜索" },
            { "Search in item descriptions", "在项目描述中搜索" },
            { "Search in metadata (exe, product)", "在元数据中搜索（exe、产品）" },
            { "Search in the Start Menu tab", "在开始菜单标签页中搜索" },
            { "Search scope: click switches folder / everywhere", "搜索范围：点击切换 文件夹 / 全部" },
            { "Search...", "搜索..." },
            { "Settings", "设置" },
            { "Show / hide bookmarks panel", "显示 / 隐藏书签面板" },
            { "Show / hide top bookmarks bar", "显示 / 隐藏顶部书签栏" },
            { "Show in Explorer", "在资源管理器中显示" },
            { "Show the welcome window again", "再次显示欢迎窗口" },
            { "Show window hotkey:", "显示窗口快捷键：" },
            { "Simple text editor", "简易文本编辑器" },
            { "Size", "大小" },
            { "Size-1", "1 x 1" },
            { "Skin & theme:", "皮肤与主题：" },
            { "Start", "开始" },
            { "Start Menu", "开始菜单" },
            { "Start Menu (all users)", "开始菜单（所有用户）" },
            { "Start Menu (local)", "开始菜单（本地）" },
            { "Start Menu (user)", "开始菜单（用户）" },
            { "Start Menu sync failed - see log.txt", "开始菜单同步失败 - 见 log.txt" },
            { "Start Menu synced:", "开始菜单已同步：" },
            { "Startup Size:", "启动尺寸：" },
            { "Support section on GitHub (README)", "GitHub 上的支持页面（README）" },
            { "Support the author", "支持作者" },
            { "Sync Start Menu every N h (0 = off):", "每 N 小时同步开始菜单（0 = 关）：" },
            { "Sync Start Menu now", "立即同步开始菜单" },
            { "Tabs Font:", "标签页字体：" },
            { "Thanks for trying Tilettes!", "感谢试用 Tilettes！" },
            { "The app periodically asks GitHub Releases for a newer version (no auto-download yet)", "应用定期询问 GitHub Releases 是否有新版本（暂不自动下载）" },
            { "The description is used by the search and pops up as a tooltip when hovering the element.", "描述用于搜索，悬停在元素上时以工具提示弹出。" },
            { "This archive has no settings.ini / records.xml - it is not a Tilettes backup.", "此压缩包没有 settings.ini / records.xml - 不是 Tilettes 备份。" },
            { "Bugs and rough edges are possible.", "可能存在错误和未完善之处。" },
            { "✅ - the corner checkmark enables adding and editing tiles", "✅ - 角落的对勾开启添加和编辑图块" },
            { "Tiles Font:", "磁贴字体：" },
            { "Tilettes", "Tilettes" },
            { "Tilettes backup archives (*.zip)|*.zip|All files (*.*)|*.*", "Tilettes 备份压缩包 (*.zip)|*.zip|所有文件 (*.*)|*.*" },
            { "Tilettes console · ", "Tilettes 控制台 · " },
            { "Tilettes rules (*.xml)|*.xml|All files (*.*)|*.*", "Tilettes 规则 (*.xml)|*.xml|所有文件 (*.*)|*.*" },
            { "UI Font:", "界面字体：" },
            { "Update", "更新" },
            { "Updates", "更新" },
            { "Version ", "版本 " },
            { "Window Position:", "窗口位置：" },
            { "Windows calculator", "Windows 计算器" },
            { "You are on the latest version: v", "已是最新版本：v" },
            { "[console process exited - press Restart]", "[控制台进程已退出 - 请按 重启]" },
            { "\nThe green Update plate has appeared in the corner.", "\n绿色“更新”按钮已出现在角落。" },
            { "box", "输入框" },
            { "columns x", "列 x" },
            { "results", "结果" },
            { "rows", "行" },
            { "sec idle", "秒无操作" },
            { "text", "文本" },
            { "♥ Donate", "♥ 捐助" },

            // Tab menus / prompts (previously hard-coded English)
            { "Create Folder", "新建文件夹" },
            { "Folder Name", "文件夹名称" },
            { "Delete Tab", "删除标签页" },
            { "Rename Tab", "重命名标签页" },
            { "Toggle Layout (Free / Grid)", "切换布局（自由 / 网格）" },
            { "Are you sure you want to delete this tab?", "确定要删除该标签页吗？" },
            { "Cannot remove the last tab.", "无法删除最后一个标签页。" },
            { "Empty", "空" },
            { "Mini Explorer", "迷你资源管理器" },
            { "Rebuild icons & paths", "重建图标和路径" },
            { "Checked: {0} · missing paths: {1} · cache files removed: {2}",
              "已检查：{0} · 丢失路径：{1} · 已删除缓存文件：{2}" },
            { "Tile label: two rows", "磁贴标签：两行" },
            { "2 rows align:", "两行对齐：" },
            { "Left", "左对齐" },
            { "Center", "居中" },
            { "Right", "右对齐" },
            { "Hide shortcut suffix ( - Shortcut)", "隐藏快捷方式后缀" },
            { "Hide file extension (.mp4)", "隐藏文件扩展名 (.mp4)" },
            { "Extra rows below:", "底部额外行数:" },
            { "Like Tilettes? Support the author:", "喜欢 Tilettes？请支持作者：" },
            { "Opens the donate section on GitHub", "打开 GitHub 上的捐赠页面" },
            { "Extra tile rows under the visible grid, same cell size; scroll down to reach them (0 = off)",
              "可见网格下方的额外图块行，大小相同；向下滚动即可到达（0 = 关）" },
            { "Past search", "历史搜索" },
            { "Command (%1 = current folder):", "命令 (%1 = 当前文件夹)：" },
            { "in bookmarks %1 = current folder", "书签中 %1 表示当前文件夹" },
            { "Regular search", "普通搜索" },
            { "New version v", "新版本 v" },
            { " is published, but it is less than a day old. It will be offered after 24 hours - antivirus false positives on fresh builds usually settle within that time.",
              " 已发布，但发布还不到一天。将在 24 小时后再提供 — 新构建的杀毒软件误报通常会在期间消除。" }
        };
    }
}
