using System;
using System.Collections.Generic;

namespace WinPanel
{
    // Japanese UI table for Loc: keys are the exact English source strings.
    public static class LangJa
    {
        public static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { " and more...", " など..." },
            { " at (", " 位置 (" },
            { " items?", " 件？" },
            { "\". Use Ctrl/Alt/Shift/Win + a letter or digit, e.g. Ctrl+Alt+P (or None).", "\"。書式: Ctrl/Alt/Shift/Win + 英数字、例: Ctrl+Alt+P（または None）。" },
            { "(empty)", "（空）" },
            { "(no other tabs)", "（他のタブなし）" },
            { "+ Save", "+ 保存" },
            { "Add Tab", "タブを追加" },
            { "Add bookmark group", "ブックマークグループを追加" },
            { "Add command", "コマンドを追加" },
            { "Add command...", "コマンドを追加..." },
            { "Add current folder", "現在のフォルダーを追加" },
            { "Add current folder to bookmarks", "現在のフォルダーをブックマークへ追加" },
            { "Add folder bookmark", "フォルダーのブックマークを追加" },
            { "Add group...", "グループを追加..." },
            { "Add to bookmarks", "ブックマークに追加" },
            { "Add type...", "種類を追加..." },
            { "After autostart - go to tray", "自動起動後 - タスクトレイへ" },
            { "All", "すべて" },
            { "Allow adding icons", "アイコンの追加を許可" },
            { "Always keep tray icon", "タスクトレイアイコンを常に表示" },
            { "An error occurred but Tilettes keeps running.", "エラーが発生しましたが、Tilettes は動作を続けています。" },
            { "Apps (system)", "アプリ（システム）" },
            { "Autostart & tray", "自動起動とトレイ" },
            { "Autostart with Windows", "Windows 起動時に自動起動" },
            { "BOOKMARKS", "ブックマーク" },
            { "Backup created:", "バックアップを作成しました:" },
            { "Backup every N days (0 = off):", "N 日ごとにバックアップ (0 = オフ):" },
            { "Backup failed - see log.txt", "バックアップ失敗 - log.txt を参照" },
            { "Backup now", "今すぐバックアップ" },
            { "Backup saved: ", "バックアップを保存しました: " },
            { "Bookmark name:", "ブックマーク名:" },
            { "Bookmarks", "ブックマーク" },
            { "Calculator", "電卓" },
            { "Cancel", "キャンセル" },
            { "Cannot parse the hotkey \"", "ホットキーを解釈できません: \"" },
            { "Cannot read the archive: ", "アーカイブを読み取れません: " },
            { "Capture the Win key", "Win キーを捕捉する" },
            { "Capture Start button click", "スタートボタンのクリックを捕捉" },
            { "Open tiles:", "タイルを開く:" },
            { "Open results:", "検索結果を開く:" },
            { "Single click", "シングルクリック" },
            { "Double click", "ダブルクリック" },
            { "How tiles open: a single click launches right away, a double click needs two clicks", "タイルの開き方：シングルクリックですぐ開く、ダブルクリックは2回クリック" },
            { "How search results open: by a single click or a double click", "検索結果の開き方：シングルクリックまたはダブルクリック" },
            { "A left click on the Start button (screen corner) opens the panel instead of the Start menu", "スタートボタン (画面の隅) の左クリックで、スタートメニューの代わりにパネルを開く" },
            { "Open Start menu", "スタートメニューを開く" },
            { "Window", "ウィンドウ" },
            { "Tile labels", "タイルラベル" },
            { "Folders", "フォルダー" },
            { "Panel & hotkeys", "パネルとホットキー" },
            { "Fonts", "フォント" },
            { "File types & explorer", "ファイルの種類とエクスプローラー" },
            { "Open folders with:", "フォルダーを開くアプリ:" },
            { "Change Icon", "アイコンの変更" },
            { "Change...", "変更..." },
            { "Check every N days:", "N 日ごとに確認:" },
            { "Check for updates automatically", "自動で更新を確認する" },
            { "Check now", "今すぐ確認" },
            { "Clear", "クリア" },
            { "Clear history", "履歴を消去" },
            { "Clear selection", "選択を解除" },
            { "Click an address to copy it", "アドレスをクリックするとコピーします" },
            { "Click to copy the address", "クリックでアドレスをコピー" },
            { "Close", "閉じる" },
            { "Close & create example tiles", "閉じてサンプルタイルを作成" },
            { "Command:", "コマンド:" },
            { "Console", "コンソール" },
            { "Copied ✓", "コピーしました ✓" },
            { "Copy folder path", "フォルダーパスをコピー" },
            { "Copy path", "パスをコピー" },
            { "Could not reach GitHub Releases - check the internet connection.", "GitHub Releases に接続できません - インターネット接続を確認してください。" },
            { "Ctrl+Click a folder opens Mini Explorer", "フォルダーを Ctrl+クリックでミニエクスプローラーを開く" },
            { "Ctrl+L or Edit - edit path · F5 - refresh · Backspace - up · Enter - open · double-click - open", "Ctrl+L または 編集 - パス編集 · F5 - 更新 · Backspace - 上へ · Enter - 開く · ダブルクリック - 開く" },
            { "Ctrl+mouse wheel - console font size", "Ctrl+ホイール - コンソールのフォントサイズ" },
            { "Current window: ", "現在のウィンドウ: " },
            { "D", "説" },
            { "Def. Item Size:", "既定のタイルサイズ:" },
            { "Desc", "説" },
            { "Description", "説明" },
            { "Description text", "説明テキスト" },
            { "Description...", "説明..." },
            { "Descriptions", "説明" },
            { "Details in log.txt", "詳細は log.txt" },
            { "Drag to resize the console", "ドラッグでコンソールの高さを変更" },
            { "Edit", "編集" },
            { "Edit command", "コマンドを編集" },
            { "Edit command...", "コマンドを編集..." },
            { "Exact", "完全一致" },
            { "Exit", "終了" },
            { "Expects a .zip created by \"Backup now\" / scheduled backup; files are unpacked into the working folder, Tilettes.exe is not replaced", "\"今すぐバックアップ\" / 定期バックアップが作成した .zip を指定してください。ファイルは作業フォルダーに展開され、Tilettes.exe は置き換えられません" },
            { "Explorer", "エクスプローラー" },
            { "Export...", "エクスポート..." },
            { "Extract failed: ", "展開に失敗しました: " },
            { "Extract here (tar)", "ここに展開 (tar)" },
            { "File Type Icons", "ファイル種別のアイコン" },
            { "File manager", "ファイルマネージャー" },
            { "File types:", "ファイルの種類:" },
            { "Folder", "フォルダー" },
            { "Found a bug or have an idea? Create an issue on GitHub:", "バグを見つけた、またはアイデアがありますか？ GitHub で issue を作成してください:" },
            { "Full backup (settings + shortcuts + bookmarks) into autoBackup\\; runs 3 minutes after launch when due", "完全バックアップ（設定 + ショートカット + ブックマーク）を autoBackup\\ へ。期限が来たら起動 3 分後に実行" },
            { "Fuzzy accuracy (0-3):", "あいまい度 (0-3):" },
            { "Grid Columns:", "グリッド列数:" },
            { "Grid Rows:", "グリッド行数:" },
            { "Grid Transp. (0-255):", "グリッド透明度 (0-255):" },
            { "Grid:", "グリッド:" },
            { "Group (empty = top level):", "グループ (空 = 最上位):" },
            { "Group name:", "グループ名:" },
            { "Icon Scale (%):", "アイコン倍率 (%):" },
            { "Icons by type...", "種類別アイコン..." },
            { "Import...", "インポート..." },
            { "Install updates automatically", "更新を自動インストール" },
            { "Just drag a shortcut or a file onto the panel - it becomes a tile.", "ショートカットやファイルをパネルへドラッグするだけ - タイルになります。" },
            { "Language:", "言語:" },
            { "Light", "ライト" },
            { "Light Theme", "ライトテーマ" },
            { "Like Tilettes? Support the author with crypto:", "Tilettes を気に入りましたか？暗号通貨で作者を支援できます:" },
            { "M", "メ" },
            { "Maintenance & Start Menu", "メンテナンスとスタートメニュー" },
            { "Match precision: exact or fuzzy (0-3)", "一致の精度: 完全またはあいまい (0-3)" },
            { "Meta", "メタ" },
            { "Metadata", "メタデータ" },
            { "Minimize instead of close", "閉じずに最小化" },
            { "More", "その他" },
            { "Move down", "下へ" },
            { "Move out of folder", "フォルダーから出す" },
            { "Move to tab", "タブへ移動" },
            { "Move up", "上へ" },
            { "New Name", "新しい名前" },
            { "New Tab Name", "新しいタブ名" },
            { "New name:", "新しい名前:" },
            { "New version available: ", "新しいバージョンがあります: " },
            { "New version available: v", "新しいバージョンがあります: v" },
            { "New window", "新しいウィンドウ" },
            { "None (dark)", "なし (ダーク)" },
            { "Notepad", "メモ帳" },
            { "Nothing was restored - see log.txt", "何も復元されませんでした - log.txt を参照" },
            { "OK", "OK" },
            { "Open", "開く" },
            { "Open With by File Type", "ファイル種別ごとの起動方法" },
            { "Open console window here", "ここでコンソールウィンドウを開く" },
            { "Open containing folder", "上位フォルダーを開く" },
            { "Open folders in:", "フォルダーを開く場所:" },
            { "Open in Explorer", "エクスプローラーで開く" },
            { "Open in Mini Explorer", "ミニエクスプローラーで開く" },
            { "Open standard", "規定の方法で開く" },
            { "Open the donate section on GitHub", "GitHub の寄付ページを開く" },
            { "Open with by type...", "種類別の起動方法..." },
            { "Paths", "パス" },
            { "Popup window", "ポップアップウィンドウ" },
            { "Pressing the Win key opens the panel instead of the Start menu", "Win キーでスタートメニューの代わりにパネルを開く" },
            { "Refresh", "更新" },
            { "Remember active tab", "アクティブなタブを記憶" },
            { "Remove", "削除" },
            { "Remove ", "削除 " },
            { "Remove from Panel", "パネルから削除" },
            { "Remove icon", "アイコンを削除" },
            { "Remove selected", "選択を削除" },
            { "Remove selected (", "選択を削除 (" },
            { "Rename", "名前の変更" },
            { "Rename bookmark", "ブックマークの名前を変更" },
            { "Rename...", "名前を変更..." },
            { "Restart", "再起動" },
            { "Restore", "表示" },
            { "Restore archive...", "アーカイブから復元..." },
            { "Restore backup", "バックアップを復元" },
            { "Restore failed: ", "復元に失敗しました: " },
            { "Restore from a backup archive", "バックアップアーカイブから復元" },
            { "Return from a folder after this many seconds without activity (0 = off)", "フォルダー内で無操作のままこの秒数経過すると戻る (0 = オフ)" },
            { "Run", "実行" },
            { "Same window", "同じウィンドウ" },
            { "Save", "保存" },
            { "Save backup", "バックアップを保存" },
            { "Save backup (zip)", "バックアップを保存 (zip)" },
            { "Save failed: ", "保存に失敗しました: " },
            { "Save search history", "検索履歴を保存" },
            { "Search", "検索" },
            { "Search files (fuzzy, any keyboard layout)", "ファイルを検索 (あいまい、どのキーレイアウトでも)" },
            { "Search fonts:", "検索フォント:" },
            { "Search history cleared.", "検索履歴を消去しました。" },
            { "Search in descriptions", "説明内を検索" },
            { "Search in exe name, product, company", "exe 名・製品・会社名を検索" },
            { "Search in full paths", "完全パス内を検索" },
            { "Search in item descriptions", "項目の説明内を検索" },
            { "Search in metadata (exe, product)", "メタデータ内を検索 (exe、製品)" },
            { "Search in the Start Menu tab", "スタートメニュータブ内を検索" },
            { "Search scope: click switches folder / everywhere", "検索範囲: クリックで フォルダー / 全体 を切替" },
            { "Search...", "検索..." },
            { "Settings", "設定" },
            { "Show / hide bookmarks panel", "ブックマークパネルの表示 / 非表示" },
            { "Show / hide top bookmarks bar", "上部ブックマークバーの表示 / 非表示" },
            { "Show in Explorer", "エクスプローラーで表示" },
            { "Show the welcome window again", "ウェルカムウィンドウをもう一度表示" },
            { "Show window hotkey:", "ウィンドウ表示ホットキー:" },
            { "Simple text editor", "シンプルなテキストエディター" },
            { "Size", "サイズ" },
            { "Size-1", "1 x 1" },
            { "Skin & theme:", "スキンとテーマ:" },
            { "Start", "スタート" },
            { "Start Menu", "スタートメニュー" },
            { "Start Menu (all users)", "スタートメニュー (全ユーザー)" },
            { "Start Menu (local)", "スタートメニュー (ローカル)" },
            { "Start Menu (user)", "スタートメニュー (ユーザー)" },
            { "Start Menu sync failed - see log.txt", "スタートメニュー同期に失敗 - log.txt を参照" },
            { "Start Menu synced:", "スタートメニューを同期しました:" },
            { "Startup Size:", "起動時サイズ:" },
            { "Support section on GitHub (README)", "GitHub のサポートページ (README)" },
            { "Support the author", "作者を支援" },
            { "Sync Start Menu every N h (0 = off):", "N 時間ごとにスタートメニューを同期 (0 = オフ):" },
            { "Sync Start Menu now", "今すぐスタートメニューを同期" },
            { "Tabs Font:", "タブのフォント:" },
            { "Thanks for trying Tilettes!", "Tilettes をお試しいただきありがとうございます！" },
            { "The app periodically asks GitHub Releases for a newer version (no auto-download yet)", "アプリは定期的に GitHub Releases へ新しいバージョンがないか確認します（自動ダウンロードは未対応）" },
            { "The description is used by the search and pops up as a tooltip when hovering the element.", "説明は検索に使われ、要素にカーソルを合わせるとツールチップとして表示されます。" },
            { "This archive has no settings.ini / records.xml - it is not a Tilettes backup.", "このアーカイブには settings.ini / records.xml がないため Tilettes のバックアップではありません。" },
            { "This is a beta version - bugs and rough edges are possible.", "これはベータ版です - バグや未完成の部分があるかもしれません。" },
            { "Tiles Font:", "タイルのフォント:" },
            { "Tilettes", "Tilettes" },
            { "Tilettes backup archives (*.zip)|*.zip|All files (*.*)|*.*", "Tilettes バックアップアーカイブ (*.zip)|*.zip|すべてのファイル (*.*)|*.*" },
            { "Tilettes console · ", "Tilettes コンソール · " },
            { "Tilettes rules (*.xml)|*.xml|All files (*.*)|*.*", "Tilettes ルール (*.xml)|*.xml|すべてのファイル (*.*)|*.*" },
            { "UI Font:", "UI のフォント:" },
            { "Update", "更新" },
            { "Updates", "更新" },
            { "Version ", "バージョン " },
            { "Wallet addresses and other ways to help live on GitHub:", "ウォレットアドレスとその他の支援方法は GitHub をご覧ください:" },
            { "Window Position:", "ウィンドウ位置:" },
            { "Windows calculator", "Windows 電卓" },
            { "You are on the latest version: v", "最新バージョンです: v" },
            { "[console process exited - press Restart]", "[コンソールのプロセスが終了 - 再起動を押してください]" },
            { "\nThe green Update plate has appeared in the corner.", "\n緑の「更新」ボタンが隅に表示されました。" },
            { "address copied to clipboard", "アドレスをクリップボードにコピーしました" },
            { "box", "入力欄" },
            { "columns x", "列 x" },
            { "results", "結果" },
            { "rows", "行" },
            { "sec idle", "秒で戻る" },
            { "text", "テキスト" },
            { "♥ Donate", "♥ 寄付" },

            // Tab menus / prompts (previously hard-coded English)
            { "Create Folder", "フォルダーを作成" },
            { "Folder Name", "フォルダー名" },
            { "Delete Tab", "タブを削除" },
            { "Rename Tab", "タブの名前を変更" },
            { "Toggle Layout (Free / Grid)", "レイアウト切替（フリー / グリッド）" },
            { "Are you sure you want to delete this tab?", "このタブを削除してもよろしいですか？" },
            { "Cannot remove the last tab.", "最後のタブは削除できません。" },
            { "Empty", "空" },
            { "Mini Explorer", "ミニエクスプローラー" },
            { "Rebuild icons & paths", "アイコンとパスを再構築" },
            { "Checked: {0} · missing paths: {1} · cache files removed: {2}",
              "確認済み: {0} · 見つからないパス: {1} · 削除されたキャッシュファイル: {2}" },
            { "Tile label: two rows", "タイルラベル：2行" },
            { "2 rows align:", "2行の配置:" },
            { "Left", "左" },
            { "Center", "中央" },
            { "Right", "右" },
            { "Hide shortcut suffix ( - Shortcut)", "ショートカット接尾辞を隠す ( - ショートカット)" },
            { "Hide file extension (.mp4)", "ファイル拡張子を隠す (.mp4)" },
            { "Extra rows below:", "下部の追加行:" },
            { "Extra tile rows under the visible grid, same cell size; scroll down to reach them (0 = off)",
              "表示グリッドの下に追加するタイル行（同じサイズ）。下にスクロールして到達 (0 = オフ)" },
            { "Past search", "過去の検索" },
            { "Command (%1 = current folder):", "コマンド (%1 = 現在のフォルダー):" },
            { "in bookmarks %1 = current folder", "ブックマークの %1 は現在のフォルダー" }
        };
    }
}
