using System;
using System.Collections.Generic;

namespace WinPanel
{
    // Spanish UI table for Loc: keys are the exact English source strings.
    public static class LangEs
    {
        public static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { " and more...", " y más..." },
            { " at (", " en (" },
            { " is already in use by another program.", " ya está en uso por otro programa." },
            { " items?", " elementos?" },
            { " was damaged and has been recreated. Details in log.txt.", " estaba dañado y se ha vuelto a crear. Detalles en log.txt." },
            { "\". Use Ctrl/Alt/Shift/Win + a letter, digit or F-key (or None).", "\". Use Ctrl/Alt/Shift/Win + una letra, un dígito o una tecla F (o Ninguno)." },
            { "(empty)", "(vacío)" },
            { "(no other tabs)", "(no hay otras pestañas)" },
            { "+ Save", "+ Guardar" },
            { "Add Tab", "Añadir pestaña" },
            { "Add bookmark group", "Añadir grupo de marcadores" },
            { "Add command", "Añadir comando" },
            { "Add command...", "Añadir comando..." },
            { "Add current folder", "Añadir carpeta actual" },
            { "Add current folder to bookmarks", "Añadir carpeta actual a marcadores" },
            { "Add folder bookmark", "Añadir marcador de carpeta" },
            { "Add group...", "Añadir grupo..." },
            { "Add to bookmarks", "Añadir a marcadores" },
            { "Add type...", "Añadir tipo..." },
            { "After autostart - go to tray", "Tras el inicio automático - ir a la bandeja" },
            { "All", "Todo" },
            { "Allow adding icons", "Permitir añadir iconos" },
            { "Always keep tray icon", "Mantener siempre el icono en la bandeja" },
            { "An error occurred but Tilettes keeps running.", "Ocurrió un error, pero Tilettes sigue ejecutándose." },
            { "Apps (system)", "Aplicaciones (sistema)" },
            { "Aura Transp. (%):", "Transp. del aura (%):" },
            { "Aura transparency of all tiles (0 = solid color, 100 = almost invisible). A single tile can set its own in the aura color dialog.", "Transparencia del aura de todos los mosaicos (0 = color sólido, 100 = casi invisible). Un mosaico individual puede definir la suya en el diálogo de color del aura." },
            { "Standard value", "Valor estándar" },
            { "Value from settings", "Valor de la configuración" },
            { "Autostart & tray", "Autoinicio y bandeja" },
            { "Autostart with Windows", "Iniciar con Windows" },
            { "BOOKMARKS", "MARCADORES" },
            { "Backup created:", "Copia de seguridad creada:" },
            { "Backup every N days (0 = off):", "Copia de seguridad cada N días (0 = desactivado):" },
            { "Backup failed - see log.txt", "Error en la copia de seguridad - ver log.txt" },
            { "Backup now", "Crear copia de seguridad ahora" },
            { "Backup saved: ", "Copia de seguridad guardada: " },
            { "Bookmark name:", "Nombre del marcador:" },
            { "Bookmarks", "Marcadores" },
            { "Calculator", "Calculadora" },
            { "Cancel", "Cancelar" },
            { "Cannot open \"", "No se puede abrir \"" },
            { "Cannot parse the hotkey \"", "No se puede analizar el atajo \"" },
            { "Cannot read the archive: ", "No se puede leer el archivo: " },
            { "Capture the Win key", "Capturar la tecla Win" },
            { "Capture Start button click", "Capturar el clic en el botón Inicio" },
            { "Click here and press the key combination: a letter, digit, F1-F24 or Space, with Ctrl/Alt/Shift/Win. Esc or × = None.", "Haga clic aquí y pulse la combinación: una letra, dígito, F1-F24 o Espacio, con Ctrl/Alt/Shift/Win. Esc o × = Ninguno." },
            { "Ctrl + right-click on a folder tile runs this command. %1 = the folder path, e.g. wt -d \"%1\" (Windows Terminal) or cmd /K cd /d \"%1\". Empty = off (the regular menu shows).", "Ctrl + clic derecho en un mosaico de carpeta ejecuta este comando. %1 = la ruta de la carpeta, p. ej. wt -d \"%1\" (Windows Terminal) o cmd /K cd /d \"%1\". Vacío = desactivado (aparece el menú normal)." },
            { "Ctrl+Rt-click console:", "Consola Ctrl+clic dcho.:" },
            { "Hotkey ", "La combinación " },
            { "Mini Explorer did not open - details in log.txt", "El mini explorador no se abrió - detalles en log.txt" },
            { "No global hotkey (None)", "Sin tecla de acceso rápido global (Ninguno)" },
            { "Open tiles:", "Abrir mosaicos:" },
            { "Open results:", "Abrir resultados:" },
            { "Single click", "Un clic" },
            { "Double click", "Doble clic" },
            { "How tiles open: a single click launches right away, a double click needs two clicks", "Cómo se abren los mosaicos: un clic abre al instante, un doble clic necesita dos clics" },
            { "How search results open: by a single click or a double click", "Cómo se abren los resultados de búsqueda: con un clic o doble clic" },
            { "A left click on the Start button (screen corner) opens the panel instead of the Start menu", "Un clic izquierdo en el botón Inicio (esquina de la pantalla) abre el panel en lugar del menú Inicio" },
            { "Open Start menu", "Abrir el menú Inicio" },
            { "Window", "Ventana" },
            { "Tile labels", "Etiquetas de mosaicos" },
            { "Folders", "Carpetas" },
            { "Panel & hotkeys", "Panel y atajos" },
            { "Fonts", "Fuentes" },
            { "File types & explorer", "Tipos de archivo y explorador" },
            { "Open folders with:", "Abrir carpetas con:" },
            { "Change Icon", "Cambiar icono" },
            { "Change...", "Cambiar..." },
            { "Check every N days:", "Comprobar cada N días:" },
            { "Check for updates automatically", "Buscar actualizaciones automáticamente" },
            { "Check now", "Comprobar ahora" },
            { "Clear", "Limpiar" },
            { "Clear history", "Borrar historial" },
            { "Clear selection", "Deseleccionar todo" },
            { "Close", "Cerrar" },
            { "Close & create example tiles", "Cerrar y crear mosaicos de ejemplo" },
            { "Command:", "Comando:" },
            { "Console", "Consola" },
            { "Copy folder path", "Copiar ruta de la carpeta" },
            { "Copy path", "Copiar ruta" },
            { "Could not reach GitHub Releases - check the internet connection.", "No se pudo conectar con GitHub Releases - comprueba la conexión a Internet." },
            { "Ctrl+Click a folder opens Mini Explorer", "Ctrl+clic en una carpeta abre el Mini Explorer" },
            { "Ctrl+L or Edit - edit path · F5 - refresh · Backspace - up · Enter - open · double-click - open", "Ctrl+L o Editar - editar ruta · F5 - actualizar · Retroceso - subir · Intro - abrir · doble clic - abrir" },
            { "Ctrl+mouse wheel - console font size", "Ctrl+rueda del ratón - tamaño de fuente de la consola" },
            { "Current window: ", "Ventana actual: " },
            { "D", "D" },
            { "Def. Item Size:", "Tamaño predet. de elemento:" },
            { "Desc", "Desc" },
            { "Description", "Descripción" },
            { "Description text", "Texto de descripción" },
            { "Description...", "Descripción..." },
            { "Descriptions", "Descripciones" },
            { "Details in log.txt", "Detalles en log.txt" },
            { "Drag to resize the console", "Arrastra para cambiar el tamaño de la consola" },
            { "Edit", "Editar" },
            { "Edit command", "Editar comando" },
            { "Edit command...", "Editar comando..." },
            { "Exact", "Exacta" },
            { "Exit", "Salir" },
            { "Expects a .zip created by \"Backup now\" / scheduled backup; files are unpacked into the working folder, Tilettes.exe is not replaced", "Espera un .zip creado por \"Crear copia de seguridad ahora\" / copia programada; los archivos se descomprimen en la carpeta de trabajo, Tilettes.exe no se reemplaza" },
            { "Explorer", "Explorador" },
            { "Export...", "Exportar..." },
            { "Extract failed: ", "Error al extraer: " },
            { "Extract here (tar)", "Extraer aquí (tar)" },
            { "File Type Icons", "Iconos por tipo de archivo" },
            { "File manager", "Gestor de archivos" },
            { "File types:", "Tipos de archivo:" },
            { "Folder", "Carpeta" },
            { "Found a bug or have an idea? Create an issue on GitHub:", "¿Encontraste un error o tienes una idea? Crea un issue en GitHub:" },
            { "Full backup (settings + shortcuts + bookmarks) into autoBackup\\; runs 3 minutes after launch when due", "Copia de seguridad completa (ajustes + accesos directos + marcadores) en autoBackup\\; se ejecuta 3 minutos después del inicio cuando corresponde" },
            { "Fuzzy accuracy (0-3):", "Precisión aproximada (0-3):" },
            { "Grid Columns:", "Columnas de la cuadrícula:" },
            { "Grid Rows:", "Filas de la cuadrícula:" },
            { "Grid Transp. (0-255):", "Transp. de la cuadrícula (0-255):" },
            { "Grid:", "Cuadrícula:" },
            { "Group (empty = top level):", "Grupo (vacío = nivel superior):" },
            { "Group name:", "Nombre del grupo:" },
            { "Icon Scale (%):", "Escala de iconos (%):" },
            { "Icons by type...", "Iconos por tipo..." },
            { "Import...", "Importar..." },
            { "Install updates automatically", "Instalar actualizaciones automáticamente" },
            { "Just drag a shortcut or a file onto the panel - it becomes a tile.", "Arrastra un acceso directo o un archivo al panel - se convierte en un mosaico." },
            { "Language:", "Idioma:" },
            { "Light", "Claro" },
            { "Light Theme", "Tema claro" },
            { "M", "M" },
            { "Maintenance & Start Menu", "Mantenimiento y menú Inicio" },
            { "Match precision: exact or fuzzy (0-3)", "Precisión de coincidencia: exacta o aproximada (0-3)" },
            { "Meta", "Meta" },
            { "Metadata", "Metadatos" },
            { "Minimize instead of close", "Minimizar en lugar de cerrar" },
            { "More", "Más" },
            { "Move down", "Mover abajo" },
            { "Move out of folder", "Sacar de la carpeta" },
            { "Move to tab", "Mover a pestaña" },
            { "Move up", "Mover arriba" },
            { "New Name", "Nombre nuevo" },
            { "New Tab Name", "Nombre de la nueva pestaña" },
            { "New name:", "Nombre nuevo:" },
            { "New version available: ", "Nueva versión disponible: " },
            { "New version available: v", "Nueva versión disponible: v" },
            { "New window", "Nueva ventana" },
            { "None (dark)", "Ninguno (oscuro)" },
            { "Notepad", "Bloc de notas" },
            { "Nothing was restored - see log.txt", "No se restauró nada - ver log.txt" },
            { "OK", "Aceptar" },
            { "Open", "Abrir" },
            { "Open With by File Type", "Abrir con según tipo de archivo" },
            { "Open console window here", "Abrir ventana de consola aquí" },
            { "Open containing folder", "Abrir carpeta contenedora" },
            { "Open folders in:", "Abrir carpetas en:" },
            { "Open in Explorer", "Abrir en Explorador" },
            { "Open in Mini Explorer", "Abrir en Mini Explorer" },
            { "Open standard", "Abrir de forma estándar" },
            { "Open with by type...", "Abrir con por tipo..." },
            { "Paths", "Rutas" },
            { "Popup window", "Ventana emergente" },
            { "Pressing the Win key opens the panel instead of the Start menu", "Pulsar la tecla Win abre el panel en lugar del menú Inicio" },
            { "Refresh", "Actualizar" },
            { "Remember active tab", "Recordar la pestaña activa" },
            { "Remove", "Quitar" },
            { "Remove ", "Quitar " },
            { "Remove from Panel", "Quitar del panel" },
            { "Remove icon", "Quitar icono" },
            { "Remove selected", "Quitar seleccionados" },
            { "Remove selected (", "Quitar seleccionados (" },
            { "Rename", "Renombrar" },
            { "Rename bookmark", "Renombrar marcador" },
            { "Rename...", "Renombrar..." },
            { "Restart", "Reiniciar" },
            { "Restore", "Restaurar" },
            { "Restore archive...", "Restaurar archivo..." },
            { "Restore backup", "Restaurar copia de seguridad" },
            { "Restore failed: ", "Error al restaurar: " },
            { "Restore from a backup archive", "Restaurar desde un archivo de copia de seguridad" },
            { "Return from a folder after this many seconds without activity (0 = off)", "Volver de una carpeta tras estos segundos sin actividad (0 = desactivado)" },
            { "Run", "Ejecutar" },
            { "Same window", "Misma ventana" },
            { "Save", "Guardar" },
            { "Save backup", "Guardar copia de seguridad" },
            { "Save backup (zip)", "Guardar copia de seguridad (zip)" },
            { "Save failed: ", "Error al guardar: " },
            { "Save search history", "Guardar historial de búsqueda" },
            { "Search", "Buscar" },
            { "Search files (fuzzy, any keyboard layout)", "Buscar archivos (aproximado, cualquier distribución del teclado)" },
            { "Search fonts:", "Fuentes de búsqueda:" },
            { "Search history cleared.", "Historial de búsqueda borrado." },
            { "Search in descriptions", "Buscar en descripciones" },
            { "Search in exe name, product, company", "Buscar en nombre del exe, producto, empresa" },
            { "Search in full paths", "Buscar en rutas completas" },
            { "Search in item descriptions", "Buscar en descripciones de elementos" },
            { "Search in metadata (exe, product)", "Buscar en metadatos (exe, producto)" },
            { "Search in the Start Menu tab", "Buscar en la pestaña del menú Inicio" },
            { "Search scope: click switches folder / everywhere", "Ámbito de búsqueda: un clic alterna carpeta / en todas partes" },
            { "Search...", "Buscar..." },
            { "Settings", "Ajustes" },
            { "Show / hide bookmarks panel", "Mostrar / ocultar panel de marcadores" },
            { "Show / hide top bookmarks bar", "Mostrar / ocultar barra de marcadores superior" },
            { "Show in Explorer", "Mostrar en Explorador" },
            { "Show the welcome window again", "Mostrar de nuevo la ventana de bienvenida" },
            { "Show window hotkey:", "Atajo para mostrar la ventana:" },
            { "Simple text editor", "Editor de texto simple" },
            { "Size", "Tamaño" },
            { "Size-1", "1 x 1" },
            { "Skin & theme:", "Apariencia y tema:" },
            { "Start", "Inicio" },
            { "Start Menu", "Menú Inicio" },
            { "Start Menu (all users)", "Menú Inicio (todos los usuarios)" },
            { "Start Menu (local)", "Menú Inicio (local)" },
            { "Start Menu (user)", "Menú Inicio (usuario)" },
            { "Start Menu sync failed - see log.txt", "Error al sincronizar el menú Inicio - ver log.txt" },
            { "Start Menu synced:", "Menú Inicio sincronizado:" },
            { "Startup Size:", "Tamaño al iniciar:" },
            { "Support section on GitHub (README)", "Sección de apoyo en GitHub (README)" },
            { "Support the author", "Apoyar al autor" },
            { "Sync Start Menu every N h (0 = off):", "Sincronizar menú Inicio cada N h (0 = desactivado):" },
            { "Sync Start Menu now", "Sincronizar menú Inicio ahora" },
            { "Tabs Font:", "Fuente de pestañas:" },
            { "Thanks for trying Tilettes!", "¡Gracias por probar Tilettes!" },
            { "The app periodically asks GitHub Releases for a newer version (no auto-download yet)", "La aplicación pregunta periódicamente a GitHub Releases por una versión más nueva (aún sin descarga automática)" },
            { "The description is used by the search and pops up as a tooltip when hovering the element.", "La descripción la usa la búsqueda y aparece como información al pasar el cursor sobre el elemento." },
            { "This archive has no settings.ini / records.xml - it is not a Tilettes backup.", "Este archivo no contiene settings.ini / records.xml - no es una copia de seguridad de Tilettes." },
            { "Bugs and rough edges are possible.", "Pueden producirse errores y detalles sin pulir." },
            { "✅ - the corner checkmark enables adding and editing tiles", "✅ - la marca de la esquina activa añadir y editar mosaicos" },
            { "Tiles Font:", "Fuente de mosaicos:" },
            { "Tilettes", "Tilettes" },
            { "Tilettes backup archives (*.zip)|*.zip|All files (*.*)|*.*", "Copias de seguridad de Tilettes (*.zip)|*.zip|Todos los archivos (*.*)|*.*" },
            { "Tilettes console · ", "Consola de Tilettes · " },
            { "Tilettes rules (*.xml)|*.xml|All files (*.*)|*.*", "Reglas de Tilettes (*.xml)|*.xml|Todos los archivos (*.*)|*.*" },
            { "UI Font:", "Fuente de la interfaz:" },
            { "Update", "Actualizar" },
            { "Updates", "Actualizaciones" },
            { "Version ", "Versión " },
            { "Window Position:", "Posición de la ventana:" },
            { "Windows calculator", "Calculadora de Windows" },
            { "You are on the latest version: v", "Estás en la última versión: v" },
            { "[console process exited - press Restart]", "[proceso de consola finalizado - pulsa Reiniciar]" },
            { "\nThe green Update plate has appeared in the corner.", "\nLa placa verde de Actualizar ha aparecido en la esquina." },
            { "box", "cuadro de búsqueda" },
            { "columns x", "columnas x" },
            { "results", "resultados" },
            { "rows", "filas" },
            { "sec idle", "seg de inactividad" },
            { "text", "texto" },
            { "♥ Donate", "♥ Donar" },

            // Tab menus / prompts (previously hard-coded English)
            { "Create Folder", "Crear carpeta" },
            { "Folder Name", "Nombre de la carpeta" },
            { "Delete Tab", "Eliminar pestaña" },
            { "Rename Tab", "Renombrar pestaña" },
            { "Toggle Layout (Free / Grid)", "Cambiar diseño (libre / cuadrícula)" },
            { "Are you sure you want to delete this tab?", "¿Seguro que quieres eliminar esta pestaña?" },
            { "Cannot remove the last tab.", "No se puede eliminar la última pestaña." },
            { "Empty", "Vacío" },
            { "Mini Explorer", "Mini explorador" },
            { "Rebuild icons & paths", "Reconstruir iconos y rutas" },
            { "Checked: {0} · missing paths: {1} · cache files removed: {2}",
              "Comprobados: {0} · rutas perdidas: {1} · archivos de caché borrados: {2}" },
            { "Tile label: two rows", "Etiqueta de mosaico: dos líneas" },
            { "2 rows align:", "Alinear 2 líneas:" },
            { "Left", "Izquierda" },
            { "Center", "Centro" },
            { "Right", "Derecha" },
            { "Hide shortcut suffix ( - Shortcut)", "Ocultar sufijo de acceso directo ( - Acceso directo)" },
            { "Hide file extension (.mp4)", "Ocultar extensión de archivo (.mp4)" },
            { "Extra rows below:", "Filas extra debajo:" },
            { "Like Tilettes? Support the author:", "¿Te gusta Tilettes? Apoya al autor:" },
            { "Opens the donate section on GitHub", "Abre la sección de donaciones en GitHub" },
            { "Extra tile rows under the visible grid, same cell size; scroll down to reach them (0 = off)",
              "Filas de mosaicos extra bajo la cuadrícula visible, del mismo tamaño; se accede desplazándose hacia abajo (0 = desactivado)" },
            { "Past search", "Búsquedas anteriores" },
            { "Command (%1 = current folder):", "Comando (%1 = carpeta actual):" },
            { "in bookmarks %1 = current folder", "en marcadores %1 = carpeta actual" },
            { "Regular search", "Búsqueda normal" },
            { "New version v", "Nueva versión v" },
            { " is published, but it is less than a day old. It will be offered after 24 hours - antivirus false positives on fresh builds usually settle within that time.",
              " está publicada, pero tiene menos de un día. Se ofrecerá después de 24 horas: los falsos positivos del antivirus en builds recientes suelen desaparecer en ese plazo." },
            { "Aura", "Aura" },
            { "Aura color...", "Color del aura..." },
            { "Background color of the element; transparency softens it over the panel.", "Color de fondo del elemento; la transparencia lo suaviza sobre el panel." },
            { "Transparency:", "Transparencia:" },
            { "Custom color...", "Color personalizado..." },
            { "Reset", "Restablecer" },
            { "New tab", "Nueva pestaña" },
            { "Close tab", "Cerrar pestaña" },
            { "Drag to resize the bookmarks panel", "Arrastrar para cambiar el ancho del panel de marcadores" },
            { "Display name:", "Nombre para mostrar:" },
            { "selected", "seleccionados" },
            { "Stop", "Detener" },
                        { "Stop the running command", "Detener el comando en ejecución" },
            { "[stopped]", "[detenido]" }
        };
    }
}
