using System;
using System.Collections.Generic;

namespace WinPanel
{
    // Brazilian Portuguese UI table for Loc: keys are the exact English source strings.
    public static class LangPt
    {
        public static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "Shut down", "Desligar" },
            { "Restart", "Reiniciar" },
            { "Sleep", "Suspender" },
            { "Hibernate", "Hibernar" },
            { "Shut down the computer?", "Desligar o computador?" },
            { "Restart the computer?", "Reiniciar o computador?" },
            { " and more...", " e mais..." },
            { " at (", " em (" },
            { " is already in use by another program.", " já está em uso por outro programa." },
            { " items?", " itens?" },
            { " was damaged and has been recreated. Details in log.txt.", " estava danificado e foi recriado. Detalhes em log.txt." },
            { "\". Use Ctrl/Alt/Shift/Win + a letter, digit or F-key (or None).", "\". Use Ctrl/Alt/Shift/Win + uma letra, um dígito ou uma tecla F (ou Nenhum)." },
            { "(empty)", "(vazio)" },
            { "(no other tabs)", "(não há outras abas)" },
            { "+ Save", "+ Salvar" },
            { "Add Tab", "Adicionar aba" },
            { "Add bookmark group", "Adicionar grupo de favoritos" },
            { "Add command", "Adicionar comando" },
            { "Add command...", "Adicionar comando..." },
            { "Add current folder", "Adicionar pasta atual" },
            { "Add current folder to bookmarks", "Adicionar pasta atual aos favoritos" },
            { "Add folder bookmark", "Adicionar favorito de pasta" },
            { "Add group...", "Adicionar grupo..." },
            { "Add to bookmarks", "Adicionar aos favoritos" },
            { "Add type...", "Adicionar tipo..." },
            { "After autostart - go to tray", "Após a inicialização automática - ir para a bandeja" },
            { "All", "Tudo" },
            { "Allow adding icons", "Permitir adicionar ícones" },
            { "Always keep tray icon", "Manter sempre o ícone na bandeja" },
            { "An error occurred but Tilettes keeps running.", "Ocorreu um erro, mas o Tilettes continua em execução." },
            { "Apps (system)", "Aplicativos (sistema)" },
            { "Aura Transp. (%):", "Transp. da aura (%):" },
            { "Aura transparency of all tiles (0 = solid color, 100 = almost invisible). A single tile can set its own in the aura color dialog.", "Transparência da aura de todos os blocos (0 = cor sólida, 100 = quase invisível). Um bloco individual pode definir a sua na janela de cor da aura." },
            { "Standard value", "Valor padrão" },
            { "Value from settings", "Valor das configurações" },
            { "Autostart & tray", "Inicialização e bandeja" },
            { "Autostart with Windows", "Iniciar com o Windows" },
            { "BOOKMARKS", "FAVORITOS" },
            { "Backup created:", "Backup criado:" },
            { "Backup every N days (0 = off):", "Backup a cada N dias (0 = desativado):" },
            { "Backup failed - see log.txt", "Falha no backup - veja log.txt" },
            { "Backup now", "Fazer backup agora" },
            { "Backup saved: ", "Backup salvo: " },
            { "Bookmark name:", "Nome do favorito:" },
            { "Bookmarks", "Favoritos" },
            { "Calculator", "Calculadora" },
            { "Cancel", "Cancelar" },
            { "Cannot open \"", "Não é possível abrir \"" },
            { "Cannot parse the hotkey \"", "Não foi possível interpretar o atalho \"" },
            { "Cannot read the archive: ", "Não foi possível ler o arquivo: " },
            { "Capture the Win key", "Capturar a tecla Win" },
            { "Capture Start button click", "Capturar o clique no botão Iniciar" },
            { "Click here and press the key combination: a letter, digit, F1-F24 or Space, with Ctrl/Alt/Shift/Win. Esc or × = None.", "Clique aqui e pressione a combinação: uma letra, dígito, F1-F24 ou Espaço, com Ctrl/Alt/Shift/Win. Esc ou × = Nenhum." },
            { "Ctrl + right-click on a folder tile runs this command. %1 = the folder path, e.g. wt -d \"%1\" (Windows Terminal) or cmd /K cd /d \"%1\". Empty = off (the regular menu shows).", "Ctrl + clique direito em um bloco de pasta executa este comando. %1 = o caminho da pasta, ex.: wt -d \"%1\" (Windows Terminal) ou cmd /K cd /d \"%1\". Vazio = desligado (o menu normal aparece)." },
            { "Ctrl+Rt-click console:", "Console Ctrl+clique dir.:" },
            { "Hotkey ", "A combinação " },
            { "Mini Explorer did not open - details in log.txt", "O mini explorador não abriu - detalhes em log.txt" },
            { "No global hotkey (None)", "Sem tecla de atalho global (Nenhum)" },
            { "Open tiles:", "Abrir blocos:" },
            { "Open results:", "Abrir resultados:" },
            { "Single click", "Clique único" },
            { "Double click", "Clique duplo" },
            { "How tiles open: a single click launches right away, a double click needs two clicks", "Como os blocos abrem: um clique único abre na hora, um clique duplo precisa de dois" },
            { "How search results open: by a single click or a double click", "Como os resultados da pesquisa abrem: com clique único ou clique duplo" },
            { "A left click on the Start button (screen corner) opens the panel instead of the Start menu", "Um clique esquerdo no botão Iniciar (canto da tela) abre o painel em vez do menu Iniciar" },
            { "Open Start menu", "Abrir o menu Iniciar" },
            { "Window", "Janela" },
            { "Tile labels", "Rótulos dos blocos" },
            { "Folders", "Pastas" },
            { "Panel & hotkeys", "Painel e atalhos" },
            { "Fonts", "Fontes" },
            { "File types & explorer", "Tipos de arquivo e explorador" },
            { "Open folders with:", "Abrir pastas com:" },
            { "Change Icon", "Alterar ícone" },
            { "Change...", "Alterar..." },
            { "Check every N days:", "Verificar a cada N dias:" },
            { "Check for updates automatically", "Verificar atualizações automaticamente" },
            { "Check now", "Verificar agora" },
            { "Clear", "Limpar" },
            { "Clear history", "Limpar histórico" },
            { "Clear selection", "Limpar seleção" },
            { "Close", "Fechar" },
            { "Close & create example tiles", "Fechar e criar mosaicos de exemplo" },
            { "Command:", "Comando:" },
            { "Console", "Console" },
            { "Copy folder path", "Copiar caminho da pasta" },
            { "Copy path", "Copiar caminho" },
            { "Could not reach GitHub Releases - check the internet connection.", "Não foi possível acessar o GitHub Releases - verifique a conexão com a internet." },
            { "Ctrl+Click a folder opens Mini Explorer", "Ctrl+clique em uma pasta abre o Mini Explorer" },
            { "Ctrl+L or Edit - edit path · F5 - refresh · Backspace - up · Enter - open · double-click - open", "Ctrl+L ou Editar - editar caminho · F5 - atualizar · Backspace - subir · Enter - abrir · clique duplo - abrir" },
            { "Ctrl+mouse wheel - console font size", "Ctrl+roda do mouse - tamanho da fonte do console" },
            { "Current window: ", "Janela atual: " },
            { "D", "D" },
            { "Def. Item Size:", "Tam. padrão do item:" },
            { "Desc", "Desc" },
            { "Description", "Descrição" },
            { "Description text", "Texto de descrição" },
            { "Description...", "Descrição..." },
            { "Descriptions", "Descrições" },
            { "Details in log.txt", "Detalhes em log.txt" },
            { "Drag to resize the console", "Arraste para redimensionar o console" },
            { "Edit", "Editar" },
            { "Edit command", "Editar comando" },
            { "Edit command...", "Editar comando..." },
            { "Exact", "Exata" },
            { "Exit", "Sair" },
            { "Expects a .zip created by \"Backup now\" / scheduled backup; files are unpacked into the working folder, Tilettes.exe is not replaced", "Espera um .zip criado por \"Fazer backup agora\" / backup programado; os arquivos são descompactados na pasta de trabalho, Tilettes.exe não é substituído" },
            { "Explorer", "Explorador" },
            { "Export...", "Exportar..." },
            { "Extract failed: ", "Falha ao extrair: " },
            { "Extract here (tar)", "Extrair aqui (tar)" },
            { "File Type Icons", "Ícones por tipo de arquivo" },
            { "File manager", "Gerenciador de arquivos" },
            { "File types:", "Tipos de arquivo:" },
            { "Folder", "Pasta" },
            { "Found a bug or have an idea? Create an issue on GitHub:", "Encontrou um bug ou tem uma ideia? Crie uma issue no GitHub:" },
            { "Full backup (settings + shortcuts + bookmarks) into autoBackup\\; runs 3 minutes after launch when due", "Backup completo (configurações + atalhos + favoritos) em autoBackup\\; roda 3 minutos após o início quando previsto" },
            { "Fuzzy accuracy (0-3):", "Precisão aproximada (0-3):" },
            { "Grid Columns:", "Colunas da grade:" },
            { "Grid Rows:", "Linhas da grade:" },
            { "Grid Transp. (0-255):", "Transp. da grade (0-255):" },
            { "Grid:", "Grade:" },
            { "Group (empty = top level):", "Grupo (vazio = nível superior):" },
            { "Group name:", "Nome do grupo:" },
            { "Icon Scale (%):", "Escala dos ícones (%):" },
            { "Icons by type...", "Ícones por tipo..." },
            { "Import...", "Importar..." },
            { "Install updates automatically", "Instalar atualizações automaticamente" },
            { "Just drag a shortcut or a file onto the panel - it becomes a tile.", "Arraste um atalho ou um arquivo para o painel - ele se torna um mosaico." },
            { "Language:", "Idioma:" },
            { "Light", "Claro" },
            { "Light Theme", "Tema claro" },
            { "M", "M" },
            { "Maintenance & Start Menu", "Manutenção e menu Iniciar" },
            { "Match precision: exact or fuzzy (0-3)", "Precisão de correspondência: exata ou aproximada (0-3)" },
            { "Meta", "Meta" },
            { "Metadata", "Metadados" },
            { "Minimize instead of close", "Minimizar em vez de fechar" },
            { "More", "Mais" },
            { "Move down", "Mover para baixo" },
            { "Move out of folder", "Mover para fora da pasta" },
            { "Move to tab", "Mover para aba" },
            { "Move up", "Mover para cima" },
            { "New Name", "Novo nome" },
            { "New Tab Name", "Nome da nova aba" },
            { "New name:", "Novo nome:" },
            { "New version available: ", "Nova versão disponível: " },
            { "New version available: v", "Nova versão disponível: v" },
            { "New window", "Nova janela" },
            { "None (dark)", "Nenhum (escuro)" },
            { "Notepad", "Bloco de notas" },
            { "Nothing was restored - see log.txt", "Nada foi restaurado - veja log.txt" },
            { "OK", "OK" },
            { "Open", "Abrir" },
            { "Open With by File Type", "Abrir com por tipo de arquivo" },
            { "Open console window here", "Abrir janela de console aqui" },
            { "Open containing folder", "Abrir pasta que o contém" },
            { "Open folders in:", "Abrir pastas em:" },
            { "Open in Explorer", "Abrir no Explorador" },
            { "Open in Mini Explorer", "Abrir no Mini Explorer" },
            { "Open standard", "Abrir de forma padrão" },
            { "Open with by type...", "Abrir com por tipo..." },
            { "Paths", "Caminhos" },
            { "Popup window", "Janela pop-up" },
            { "Pressing the Win key opens the panel instead of the Start menu", "Pressionar a tecla Win abre o painel em vez do menu Iniciar" },
            { "Refresh", "Atualizar" },
            { "Remember active tab", "Lembrar a aba ativa" },
            { "Remove", "Remover" },
            { "Remove ", "Remover " },
            { "Remove from Panel", "Remover do painel" },
            { "Remove icon", "Remover ícone" },
            { "Remove selected", "Remover selecionados" },
            { "Remove selected (", "Remover selecionados (" },
            { "Rename", "Renomear" },
            { "Rename bookmark", "Renomear favorito" },
            { "Rename...", "Renomear..." },
            { "Restart", "Reiniciar" },
            { "Restore", "Restaurar" },
            { "Restore archive...", "Restaurar arquivo..." },
            { "Restore backup", "Restaurar backup" },
            { "Restore failed: ", "Falha ao restaurar: " },
            { "Restore from a backup archive", "Restaurar de um arquivo de backup" },
            { "Return from a folder after this many seconds without activity (0 = off)", "Voltar de uma pasta após este número de segundos sem atividade (0 = desativado)" },
            { "Run", "Executar" },
            { "Same window", "Mesma janela" },
            { "Save", "Salvar" },
            { "Save backup", "Salvar backup" },
            { "Save backup (zip)", "Salvar backup (zip)" },
            { "Save failed: ", "Falha ao salvar: " },
            { "Save search history", "Salvar histórico de pesquisa" },
            { "Search", "Pesquisar" },
            { "Search files (fuzzy, any keyboard layout)", "Pesquisar arquivos (aproximado, qualquer layout de teclado)" },
            { "Search fonts:", "Fontes da pesquisa:" },
            { "Search history cleared.", "Histórico de pesquisa limpo." },
            { "Search in descriptions", "Pesquisar em descrições" },
            { "Search in exe name, product, company", "Pesquisar em nome do exe, produto, empresa" },
            { "Search in full paths", "Pesquisar em caminhos completos" },
            { "Search in item descriptions", "Pesquisar em descrições de itens" },
            { "Search in metadata (exe, product)", "Pesquisar em metadados (exe, produto)" },
            { "Search in the Start Menu tab", "Pesquisar na aba do menu Iniciar" },
            { "Search scope: click switches folder / everywhere", "Escopo da pesquisa: um clique alterna pasta / em todos os lugares" },
            { "Search...", "Pesquisar..." },
            { "Settings", "Configurações" },
            { "Show / hide bookmarks panel", "Mostrar / ocultar painel de favoritos" },
            { "Show / hide top bookmarks bar", "Mostrar / ocultar barra de favoritos superior" },
            { "Show in Explorer", "Mostrar no Explorador" },
            { "Show the welcome window again", "Mostrar a janela de boas-vindas novamente" },
            { "Show window hotkey:", "Atalho para mostrar a janela:" },
            { "Simple text editor", "Editor de texto simples" },
            { "Size", "Tamanho" },
            { "Size-1", "1 x 1" },
            { "Skin & theme:", "Aparência e tema:" },
            { "Start", "Iniciar" },
            { "Start Menu", "Menu Iniciar" },
            { "Start Menu (all users)", "Menu Iniciar (todos os usuários)" },
            { "Start Menu (local)", "Menu Iniciar (local)" },
            { "Start Menu (user)", "Menu Iniciar (usuário)" },
            { "Start Menu sync failed - see log.txt", "Falha ao sincronizar o menu Iniciar - veja log.txt" },
            { "Start Menu synced:", "Menu Iniciar sincronizado:" },
            { "Startup Size:", "Tamanho na inicialização:" },
            { "Support section on GitHub (README)", "Seção de apoio no GitHub (README)" },
            { "Support the author", "Apoiar o autor" },
            { "Sync Start Menu every N h (0 = off):", "Sincronizar menu Iniciar a cada N h (0 = desativado):" },
            { "Sync Start Menu now", "Sincronizar menu Iniciar agora" },
            { "Tabs Font:", "Fonte das abas:" },
            { "Thanks for trying Tilettes!", "Obrigado por experimentar o Tilettes!" },
            { "The app periodically asks GitHub Releases for a newer version (no auto-download yet)", "O aplicativo consulta periodicamente o GitHub Releases sobre uma versão mais nova (ainda sem download automático)" },
            { "The description is used by the search and pops up as a tooltip when hovering the element.", "A descrição é usada pela pesquisa e aparece como uma dica ao passar o mouse sobre o item." },
            { "This archive has no settings.ini / records.xml - it is not a Tilettes backup.", "Este arquivo não contém settings.ini / records.xml - não é um backup do Tilettes." },
            { "Bugs and rough edges are possible.", "Bugs e detalhes inacabados são possíveis." },
            { "✅ - the corner checkmark enables adding and editing tiles", "✅ - o visto no canto ativa adicionar e editar blocos" },
            { "Tiles Font:", "Fonte dos mosaicos:" },
            { "Tilettes", "Tilettes" },
            { "Tilettes backup archives (*.zip)|*.zip|All files (*.*)|*.*", "Backups do Tilettes (*.zip)|*.zip|Todos os arquivos (*.*)|*.*" },
            { "Tilettes console · ", "Console do Tilettes · " },
            { "Tilettes rules (*.xml)|*.xml|All files (*.*)|*.*", "Regras do Tilettes (*.xml)|*.xml|Todos os arquivos (*.*)|*.*" },
            { "UI Font:", "Fonte da interface:" },
            { "Update", "Atualizar" },
            { "Updates", "Atualizações" },
            { "Version ", "Versão " },
            { "Window Position:", "Posição da janela:" },
            { "Windows calculator", "Calculadora do Windows" },
            { "You are on the latest version: v", "Você está na versão mais recente: v" },
            { "[console process exited - press Restart]", "[processo do console encerrado - pressione Reiniciar]" },
            { "\nThe green Update plate has appeared in the corner.", "\nA placa verde de Atualizar apareceu no canto." },
            { "box", "caixa de pesquisa" },
            { "columns x", "colunas x" },
            { "results", "resultados" },
            { "rows", "linhas" },
            { "sec idle", "seg de inatividade" },
            { "text", "texto" },
            { "♥ Donate", "♥ Doar" },

            // Tab menus / prompts (previously hard-coded English)
            { "Create Folder", "Criar pasta" },
            { "Folder Name", "Nome da pasta" },
            { "Delete Tab", "Eliminar aba" },
            { "Rename Tab", "Renomear aba" },
            { "Toggle Layout (Free / Grid)", "Alternar disposição (livre / grade)" },
            { "Are you sure you want to delete this tab?", "Tem a certeza de que quer eliminar esta aba?" },
            { "Cannot remove the last tab.", "Não é possível eliminar a última aba." },
            { "Empty", "Vazio" },
            { "Mini Explorer", "Mini explorador" },
            { "Rebuild icons & paths", "Reconstruir ícones e caminhos" },
            { "Checked: {0} · missing paths: {1} · cache files removed: {2}",
              "Verificados: {0} · caminhos perdidos: {1} · ficheiros de cache removidos: {2}" },
            { "Tile label: two rows", "Rótulo do bloco: duas linhas" },
            { "2 rows align:", "Alinhar 2 linhas:" },
            { "Left", "Esquerda" },
            { "Center", "Centro" },
            { "Right", "Direita" },
            { "Hide shortcut suffix ( - Shortcut)", "Ocultar sufixo de atalho ( - Atalho)" },
            { "Hide file extension (.mp4)", "Ocultar extensão de arquivo (.mp4)" },
            { "Extra rows below:", "Linhas extras abaixo:" },
            { "Like Tilettes? Support the author:", "Gosta do Tilettes? Apoie o autor:" },
            { "Opens the donate section on GitHub", "Abre a seção de doações no GitHub" },
            { "Extra tile rows under the visible grid, same cell size; scroll down to reach them (0 = off)",
              "Linhas de blocos extras abaixo da grade visível, do mesmo tamanho; acessíveis rolando para baixo (0 = desativado)" },
            { "Past search", "Pesquisas anteriores" },
            { "Command (%1 = current folder):", "Comando (%1 = pasta atual):" },
            { "in bookmarks %1 = current folder", "nos favoritos %1 = pasta atual" },
            { "Regular search", "Pesquisa normal" },
            { "New version v", "Nova versão v" },
            { " is published, but it is less than a day old. It will be offered after 24 hours - antivirus false positives on fresh builds usually settle within that time.",
              " está publicada, mas tem menos de um dia. Será oferecida após 24 horas - falsos positivos de antivírus em builds recentes costumam se resolver nesse prazo." },
            { "Aura", "Aura" },
            { "Aura color...", "Cor da aura..." },
            { "Background color of the element; transparency softens it over the panel.", "Cor de fundo do elemento; a transparência o suaviza sobre o painel." },
            { "Transparency:", "Transparência:" },
            { "Custom color...", "Cor personalizada..." },
            { "Reset", "Redefinir" },
            { "New tab", "Nova aba" },
            { "Close tab", "Fechar aba" },
            { "Drag to resize the bookmarks panel", "Arraste para redimensionar o painel de favoritos" },
            { "Display name:", "Nome de exibição:" },
            { "selected", "selecionados" },
            { "Stop", "Parar" },
                        { "Stop the running command", "Parar o comando em execução" },
            { "[stopped]", "[parado]" },
            { "Sync user Start", "Sincronizar o Iniciar do usuário" },
            { "Close & sync user Start", "Fechar e sincronizar o Iniciar do usuário" },
            { "Could not export the Start layout - see log.txt.", "Não foi possível exportar o layout do menu Iniciar - veja log.txt." },
            { "No Start tiles found - Windows 11 or the Start menu layer is damaged.", "Nenhum bloco do menu Iniciar encontrado - Windows 11 ou camada do menu Iniciar danificada." },
            { "Added: {0}", "Adicionados: {0}" },
            { "Skipped (pinned sites, tile folders): {0}", "Ignorados (sites fixados, pastas de blocos): {0}" },
            { "Missing on this computer: {0}", "Não existem neste computador: {0}" },
            { "User Start", "Iniciar do usuário" },
            { "Create Group", "Criar grupo" },
            { "Name the group", "Nomear o grupo" },
            { "Rename group", "Renomear grupo" },
            { "Delete group", "Eliminar grupo" },
            { "Group size: auto", "Tamanho do grupo: automático" },
            { "Fix width...", "Fixar largura..." },
            { "Fix width and height...", "Fixar largura e altura..." },
            { "Width in cells", "Largura em células" },
            { "Size as WxH, e.g. 8x3", "Tamanho como LxA, ex. 8x3" }
        };
    }
}
