using System;
using System.Collections.Generic;

namespace WinPanel
{
    // French UI table for Loc: keys are the exact English source strings.
    public static class LangFr
    {
        public static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "Shut down", "Arrêter" },
            { "Restart", "Redémarrer" },
            { "Sleep", "Mettre en veille" },
            { "Hibernate", "Mettre en veille prolongée" },
            { "Shut down the computer?", "Éteindre l'ordinateur ?" },
            { "Restart the computer?", "Redémarrer l'ordinateur ?" },
            { " and more...", " et plus..." },
            { " at (", " à (" },
            { " is already in use by another program.", " est déjà utilisé par un autre programme." },
            { " items?", " éléments ?" },
            { " was damaged and has been recreated. Details in log.txt.", " était endommagé et a été recréé. Détails dans log.txt." },
            { "\". Use Ctrl/Alt/Shift/Win + a letter, digit or F-key (or None).", "\". Format : Ctrl/Alt/Shift/Win + lettre, chiffre ou touche F (ou None)." },
            { "(empty)", "(vide)" },
            { "(no other tabs)", "(aucun autre onglet)" },
            { "+ Save", "+ Enregistrer" },
            { "Add Tab", "Ajouter un onglet" },
            { "Add bookmark group", "Ajouter un groupe de favoris" },
            { "Add command", "Ajouter une commande" },
            { "Add command...", "Ajouter une commande..." },
            { "Add current folder", "Ajouter le dossier courant" },
            { "Add current folder to bookmarks", "Ajouter le dossier courant aux favoris" },
            { "Add folder bookmark", "Ajouter un favori dossier" },
            { "Add group...", "Ajouter un groupe..." },
            { "Add to bookmarks", "Ajouter aux favoris" },
            { "Add type...", "Ajouter un type..." },
            { "After autostart - go to tray", "Après le démarrage auto - dans la zone de notification" },
            { "All", "Tout" },
            { "Allow adding icons", "Autoriser l'ajout d'icônes" },
            { "Always keep tray icon", "Toujours garder l'icône de notification" },
            { "An error occurred but Tilettes keeps running.", "Une erreur s'est produite mais Tilettes continue de fonctionner." },
            { "Apps (system)", "Applications (système)" },
            { "Aura Transp. (%):", "Transp. de l'aura (%) :" },
            { "Aura transparency of all tiles (0 = solid color, 100 = almost invisible). A single tile can set its own in the aura color dialog.", "Transparence de l'aura de toutes les tuiles (0 = couleur pleine, 100 = presque invisible). Une tuile seule peut définir la sienne dans la fenêtre de couleur d'aura." },
            { "Standard value", "Valeur standard" },
            { "Value from settings", "Valeur des paramètres" },
            { "Autostart & tray", "Démarrage auto & notification" },
            { "Autostart with Windows", "Lancer avec Windows" },
            { "BOOKMARKS", "FAVORIS" },
            { "Backup created:", "Sauvegarde créée :" },
            { "Backup every N days (0 = off):", "Sauvegarde tous les N jours (0 = off) :" },
            { "Backup failed - see log.txt", "Échec de la sauvegarde - voir log.txt" },
            { "Backup now", "Sauvegarder maintenant" },
            { "Backup saved: ", "Sauvegarde enregistrée : " },
            { "Bookmark name:", "Nom du favori :" },
            { "Bookmarks", "Favoris" },
            { "Calculator", "Calculatrice" },
            { "Cancel", "Annuler" },
            { "Cannot open \"", "Impossible d'ouvrir \"" },
            { "Cannot parse the hotkey \"", "Raccourci illisible : \"" },
            { "Cannot read the archive: ", "Impossible de lire l'archive : " },
            { "Capture the Win key", "Capturer la touche Win" },
            { "Capture Start button click", "Capturer le clic sur le bouton Démarrer" },
            { "Click here and press the key combination: a letter, digit, F1-F24 or Space, with Ctrl/Alt/Shift/Win. Esc or × = None.", "Cliquez ici et appuyez sur la combinaison : lettre, chiffre, F1-F24 ou Espace, avec Ctrl/Alt/Shift/Win. Échap ou × = None." },
            { "Ctrl + right-click on a folder tile runs this command. %1 = the folder path, e.g. wt -d \"%1\" (Windows Terminal) or cmd /K cd /d \"%1\". Empty = off (the regular menu shows).", "Ctrl + clic droit sur une tuile de dossier exécute cette commande. %1 = le chemin du dossier, p. ex. wt -d \"%1\" (Windows Terminal) ou cmd /K cd /d \"%1\". Vide = désactivé (le menu normal s'affiche)." },
            { "Ctrl+Rt-click console:", "Console Ctrl+clic droit :" },
            { "Hotkey ", "Le raccourci " },
            { "Mini Explorer did not open - details in log.txt", "Le mini-explorateur ne s'est pas ouvert - détails dans log.txt" },
            { "No global hotkey (None)", "Aucun raccourci global (None)" },
            { "Open tiles:", "Ouvrir les tuiles :" },
            { "Open results:", "Ouvrir les résultats :" },
            { "Single click", "Clic simple" },
            { "Double click", "Double clic" },
            { "How tiles open: a single click launches right away, a double click needs two clicks", "Comment ouvrir les tuiles : un clic simple ouvre aussitôt, un double clic en demande deux" },
            { "How search results open: by a single click or a double click", "Comment ouvrir les résultats de recherche : par un clic simple ou un double clic" },
            { "A left click on the Start button (screen corner) opens the panel instead of the Start menu", "Un clic gauche sur le bouton Démarrer (coin de l'écran) ouvre le panneau au lieu du menu Démarrer" },
            { "Open Start menu", "Ouvrir le menu Démarrer" },
            { "Window", "Fenêtre" },
            { "Tile labels", "Libellés des tuiles" },
            { "Folders", "Dossiers" },
            { "Panel & hotkeys", "Panneau & raccourcis" },
            { "Fonts", "Polices" },
            { "File types & explorer", "Types de fichiers & explorateur" },
            { "Open folders with:", "Ouvrir les dossiers avec :" },
            { "Change Icon", "Changer l'icône" },
            { "Change...", "Modifier..." },
            { "Check every N days:", "Vérifier tous les N jours :" },
            { "Check for updates automatically", "Rechercher les mises à jour automatiquement" },
            { "Check now", "Vérifier maintenant" },
            { "Clear", "Effacer" },
            { "Clear history", "Effacer l'historique" },
            { "Clear selection", "Effacer la sélection" },
            { "Close", "Fermer" },
            { "Close & create example tiles", "Fermer & créer des tuiles d'exemple" },
            { "Command:", "Commande :" },
            { "Console", "Console" },
            { "Copy folder path", "Copier le chemin du dossier" },
            { "Copy path", "Copier le chemin" },
            { "Could not reach GitHub Releases - check the internet connection.", "Impossible de joindre GitHub Releases - vérifiez la connexion Internet." },
            { "Ctrl+Click a folder opens Mini Explorer", "Ctrl+clic sur un dossier ouvre le mini-explorateur" },
            { "Ctrl+L or Edit - edit path · F5 - refresh · Backspace - up · Enter - open · double-click - open", "Ctrl+L ou Modifier - modifier le chemin · F5 - actualiser · Retour arrière - remonter · Entrée - ouvrir · double-clic - ouvrir" },
            { "Ctrl+mouse wheel - console font size", "Ctrl+molette - taille de police de la console" },
            { "Current window: ", "Fenêtre actuelle : " },
            { "D", "D" },
            { "Def. Item Size:", "Taille déf. des tuiles :" },
            { "Desc", "Descri" },
            { "Description", "Description" },
            { "Description text", "Texte de description" },
            { "Description...", "Description..." },
            { "Descriptions", "Descriptions" },
            { "Details in log.txt", "Détails dans log.txt" },
            { "Drag to resize the console", "Faites glisser pour redimensionner la console" },
            { "Edit", "Modifier" },
            { "Edit command", "Modifier la commande" },
            { "Edit command...", "Modifier la commande..." },
            { "Exact", "Exact" },
            { "Exit", "Quitter" },
            { "Expects a .zip created by \"Backup now\" / scheduled backup; files are unpacked into the working folder, Tilettes.exe is not replaced", "Attend un .zip créé par \"Sauvegarder maintenant\" / la sauvegarde planifiée ; les fichiers sont décompressés dans le dossier de travail, Tilettes.exe n'est pas remplacé" },
            { "Explorer", "Explorateur" },
            { "Export...", "Exporter..." },
            { "Extract failed: ", "Échec de l'extraction : " },
            { "Extract here (tar)", "Extraire ici (tar)" },
            { "File Type Icons", "Icônes par type de fichier" },
            { "File manager", "Gestionnaire de fichiers" },
            { "File types:", "Types de fichiers :" },
            { "Folder", "Dossier" },
            { "Found a bug or have an idea? Create an issue on GitHub:", "Un bug ou une idée ? Créez une issue sur GitHub :" },
            { "Full backup (settings + shortcuts + bookmarks) into autoBackup\\; runs 3 minutes after launch when due", "Sauvegarde complète (réglages + raccourcis + favoris) dans autoBackup\\ ; lancée 3 minutes après le démarrage quand due" },
            { "Fuzzy accuracy (0-3):", "Précision floue (0-3) :" },
            { "Grid Columns:", "Colonnes de la grille :" },
            { "Grid Rows:", "Lignes de la grille :" },
            { "Grid Transp. (0-255):", "Transp. grille (0-255) :" },
            { "Grid:", "Grille :" },
            { "Group (empty = top level):", "Groupe (vide = premier niveau) :" },
            { "Group name:", "Nom du groupe :" },
            { "Icon Scale (%):", "Échelle des icônes (%) :" },
            { "Icons by type...", "Icônes par type..." },
            { "Import...", "Importer..." },
            { "Install updates automatically", "Installer les mises à jour automatiquement" },
            { "Just drag a shortcut or a file onto the panel - it becomes a tile.", "Glissez simplement un raccourci ou un fichier sur le panneau - il devient une tuile." },
            { "Language:", "Langue :" },
            { "Light", "Clair" },
            { "Light Theme", "Thème clair" },
            { "M", "M" },
            { "Maintenance & Start Menu", "Maintenance & Menu Démarrer" },
            { "Match precision: exact or fuzzy (0-3)", "Précision de correspondance : exacte ou floue (0-3)" },
            { "Meta", "Méta" },
            { "Metadata", "Métadonnées" },
            { "Minimize instead of close", "Réduire au lieu de fermer" },
            { "More", "Plus" },
            { "Move down", "Descendre" },
            { "Move out of folder", "Sortir du dossier" },
            { "Move to tab", "Déplacer vers l'onglet" },
            { "Move up", "Monter" },
            { "New Name", "Nouveau nom" },
            { "New Tab Name", "Nom du nouvel onglet" },
            { "New name:", "Nouveau nom :" },
            { "New version available: ", "Nouvelle version disponible : " },
            { "New version available: v", "Nouvelle version disponible : v" },
            { "New window", "Nouvelle fenêtre" },
            { "None (dark)", "Aucun (sombre)" },
            { "Notepad", "Bloc-notes" },
            { "Nothing was restored - see log.txt", "Rien n'a été restauré - voir log.txt" },
            { "OK", "OK" },
            { "Open", "Ouvrir" },
            { "Open With by File Type", "Ouvrir avec par type de fichier" },
            { "Open console window here", "Ouvrir une fenêtre console ici" },
            { "Open containing folder", "Ouvrir le dossier parent" },
            { "Open folders in:", "Ouvrir les dossiers dans :" },
            { "Open in Explorer", "Ouvrir dans l'Explorateur" },
            { "Open in Mini Explorer", "Ouvrir dans le mini-explorateur" },
            { "Open standard", "Ouvrir (standard)" },
            { "Open with by type...", "Ouvrir avec par type..." },
            { "Paths", "Chemins" },
            { "Popup window", "Fenêtre contextuelle" },
            { "Pressing the Win key opens the panel instead of the Start menu", "La touche Win ouvre le panneau au lieu du menu Démarrer" },
            { "Refresh", "Actualiser" },
            { "Remember active tab", "Mémoriser l'onglet actif" },
            { "Remove", "Supprimer" },
            { "Remove ", "Supprimer " },
            { "Remove from Panel", "Retirer du panneau" },
            { "Remove icon", "Retirer l'icône" },
            { "Remove selected", "Supprimer la sélection" },
            { "Remove selected (", "Supprimer la sélection (" },
            { "Rename", "Renommer" },
            { "Rename bookmark", "Renommer le favori" },
            { "Rename...", "Renommer..." },
            { "Restore", "Afficher" },
            { "Restore archive...", "Restaurer l'archive..." },
            { "Restore backup", "Restaurer la sauvegarde" },
            { "Restore failed: ", "Échec de la restauration : " },
            { "Restore from a backup archive", "Restaurer depuis une archive de sauvegarde" },
            { "Return from a folder after this many seconds without activity (0 = off)", "Sortir d'un dossier après autant de secondes sans activité (0 = off)" },
            { "Run", "Exécuter" },
            { "Same window", "Même fenêtre" },
            { "Save", "Enregistrer" },
            { "Save backup", "Enregistrer la sauvegarde" },
            { "Save backup (zip)", "Enregistrer la sauvegarde (zip)" },
            { "Save failed: ", "Échec de l'enregistrement : " },
            { "Save search history", "Enregistrer l'historique de recherche" },
            { "Search", "Rechercher" },
            { "Search files (fuzzy, any keyboard layout)", "Rechercher des fichiers (flou, toute disposition clavier)" },
            { "Search fonts:", "Polices de recherche :" },
            { "Search history cleared.", "Historique de recherche effacé." },
            { "Search in descriptions", "Rechercher dans les descriptions" },
            { "Search in exe name, product, company", "Rechercher dans le nom exe, produit, société" },
            { "Search in full paths", "Rechercher dans les chemins complets" },
            { "Search in item descriptions", "Rechercher dans les descriptions des éléments" },
            { "Search in metadata (exe, product)", "Rechercher dans les métadonnées (exe, produit)" },
            { "Search in the Start Menu tab", "Rechercher dans l'onglet Menu Démarrer" },
            { "Search scope: click switches folder / everywhere", "Portée : un clic bascule dossier / partout" },
            { "Search...", "Rechercher..." },
            { "Settings", "Paramètres" },
            { "Show / hide bookmarks panel", "Afficher / masquer le volet des favoris" },
            { "Show / hide top bookmarks bar", "Afficher / masquer la barre de favoris supérieure" },
            { "Show in Explorer", "Afficher dans l'Explorateur" },
            { "Show the welcome window again", "Réafficher la fenêtre de bienvenue" },
            { "Show window hotkey:", "Raccourci d'affichage :" },
            { "Simple text editor", "Éditeur de texte simple" },
            { "Size", "Taille" },
            { "Size-1", "1 x 1" },
            { "Skin & theme:", "Habillage & thème :" },
            { "Start", "Démarrer" },
            { "Start Menu", "Menu Démarrer" },
            { "Start Menu (all users)", "Menu Démarrer (tous les utilisateurs)" },
            { "Start Menu (local)", "Menu Démarrer (local)" },
            { "Start Menu (user)", "Menu Démarrer (utilisateur)" },
            { "Start Menu sync failed - see log.txt", "Échec de la synchro du Menu Démarrer - voir log.txt" },
            { "Start Menu synced:", "Menu Démarrer synchronisé :" },
            { "Startup Size:", "Taille au démarrage :" },
            { "Support section on GitHub (README)", "Section de soutien sur GitHub (README)" },
            { "Support the author", "Soutenir l'auteur" },
            { "Sync Start Menu every N h (0 = off):", "Synchro Menu Démarrer toutes les N h (0 = off) :" },
            { "Sync Start Menu now", "Synchroniser le Menu Démarrer" },
            { "Tabs Font:", "Police des onglets :" },
            { "Thanks for trying Tilettes!", "Merci d'essayer Tilettes !" },
            { "The app periodically asks GitHub Releases for a newer version (no auto-download yet)", "L'application interroge périodiquement GitHub Releases pour une version plus récente (pas encore de téléchargement auto)" },
            { "The description is used by the search and pops up as a tooltip when hovering the element.", "La description est utilisée par la recherche et apparaît en infobulle au survol de l'élément." },
            { "This archive has no settings.ini / records.xml - it is not a Tilettes backup.", "Cette archive ne contient pas settings.ini / records.xml - ce n'est pas une sauvegarde Tilettes." },
            { "Bugs and rough edges are possible.", "Des bugs et des imperfections sont possibles." },
            { "✅ - the corner checkmark enables adding and editing tiles", "✅ - la coche dans le coin active l'ajout et la modification des tuiles" },
            { "Tiles Font:", "Police des tuiles :" },
            { "Tilettes", "Tilettes" },
            { "Tilettes backup archives (*.zip)|*.zip|All files (*.*)|*.*", "Archives de sauvegarde Tilettes (*.zip)|*.zip|Tous les fichiers (*.*)|*.*" },
            { "Tilettes console · ", "Console Tilettes · " },
            { "Tilettes rules (*.xml)|*.xml|All files (*.*)|*.*", "Règles Tilettes (*.xml)|*.xml|Tous les fichiers (*.*)|*.*" },
            { "UI Font:", "Police de l'interface :" },
            { "Update", "Mettre à jour" },
            { "Updates", "Mises à jour" },
            { "Version ", "Version " },
            { "Window Position:", "Position de la fenêtre :" },
            { "Windows calculator", "Calculatrice Windows" },
            { "You are on the latest version: v", "Vous êtes sur la dernière version : v" },
            { "[console process exited - press Restart]", "[processus console terminé - appuyez sur Redémarrer]" },
            { "\nThe green Update plate has appeared in the corner.", "\nLa pastille verte « Mettre à jour » est apparue dans le coin." },
            { "box", "champ" },
            { "columns x", "colonnes x" },
            { "results", "résultats" },
            { "rows", "lignes" },
            { "sec idle", "s d'inactivité" },
            { "text", "texte" },
            { "♥ Donate", "♥ Faire un don" },

            // Tab menus / prompts (previously hard-coded English)
            { "Create Folder", "Créer un dossier" },
            { "Folder Name", "Nom du dossier" },
            { "Delete Tab", "Supprimer l'onglet" },
            { "Rename Tab", "Renommer l'onglet" },
            { "Toggle Layout (Free / Grid)", "Basculer la disposition (libre / grille)" },
            { "Are you sure you want to delete this tab?", "Voulez-vous vraiment supprimer cet onglet ?" },
            { "Cannot remove the last tab.", "Impossible de supprimer le dernier onglet." },
            { "Empty", "Vide" },
            { "Mini Explorer", "Mini-explorateur" },
            { "Rebuild icons & paths", "Reconstruire les icônes et les chemins" },
            { "Checked: {0} · missing paths: {1} · cache files removed: {2}",
              "Vérifiés : {0} · chemins manquants : {1} · fichiers de cache supprimés : {2}" },
            { "Tile label: two rows", "Libellé de tuile : deux lignes" },
            { "2 rows align:", "Alignement 2 lignes :" },
            { "Left", "Gauche" },
            { "Center", "Centre" },
            { "Right", "Droite" },
            { "Hide shortcut suffix ( - Shortcut)", "Masquer le suffixe de raccourci ( - Raccourci)" },
            { "Hide file extension (.mp4)", "Masquer l'extension du fichier (.mp4)" },
            { "Extra rows below:", "Rangées sous la grille :" },
            { "Like Tilettes? Support the author:", "Tu aimes Tilettes ? Soutenez l'auteur :" },
            { "Opens the donate section on GitHub", "Ouvre la section don sur GitHub" },
            { "Virtual desktops - move the panel when shown", "Bureaux virtuels - déplacer le panneau à l'affichage" },
            { "When the desktop COM component is unavailable, the window is recreated on every show - this can occasionally cause a repaint glitch. Leave off unless you use several virtual desktops.", "Quand le composant COM des bureaux est indisponible, la fenêtre est recréée à chaque affichage - cela peut occasionnellement provoquer un défaut de redessin. À laisser désactivé si vous n'utilisez pas plusieurs bureaux virtuels." },
            { "Extra tile rows under the visible grid, same cell size; scroll down to reach them (0 = off)",
              "Rangées de tuiles supplémentaires sous la grille visible, même taille ; atteignables en défilant vers le bas (0 = off)" },
            { "Past search", "Recherches récentes" },
            { "Command (%1 = current folder):", "Commande (%1 = dossier actuel) :" },
            { "in bookmarks %1 = current folder", "dans les favoris %1 = dossier actuel" },
            { "Regular search", "Recherche normale" },
            { "New version v", "Nouvelle version v" },
            { " is published, but it is less than a day old. It will be offered after 24 hours - antivirus false positives on fresh builds usually settle within that time.",
              " est publiée, mais elle a moins d'un jour. Elle sera proposée après 24 heures - les faux positifs antivirus sur les versions récentes disparaissent généralement dans ce délai." },
            { "Aura", "Aura" },
            { "Aura color...", "Couleur de l'aura..." },
            { "Background color of the element; transparency softens it over the panel.", "Couleur d'arrière-plan de l'élément ; la transparence l'adoucit sur le panneau." },
            { "Transparency:", "Transparence :" },
            { "Custom color...", "Couleur personnalisée..." },
            { "Reset", "Réinitialiser" },
            { "New tab", "Nouvel onglet" },
            { "Close tab", "Fermer l'onglet" },
            { "Drag to resize the bookmarks panel", "Faites glisser pour redimensionner le panneau des favoris" },
            { "Display name:", "Nom affiché :" },
            { "selected", "sélectionnés" },
            { "Stop", "Arrêter" },
                        { "Stop the running command", "Arrêter la commande en cours" },
            { "[stopped]", "[arrêté]" },
            { "Sync user Start", "Synchroniser le Démarrage de l'utilisateur" },
            { "Close & sync user Start", "Fermer et synchroniser le Démarrage de l'utilisateur" },
            { "Could not export the Start layout - see log.txt.", "Impossible d'exporter la disposition du menu Démarrer - voir log.txt." },
            { "No Start tiles found - Windows 11 or the Start menu layer is damaged.", "Aucune tuile du menu Démarrer trouvée - Windows 11 ou couche du menu Démarrer endommagée." },
            { "Added: {0}", "Ajoutées : {0}" },
            { "Skipped (pinned sites, tile folders): {0}", "Ignorées (sites épinglés, dossiers de tuiles) : {0}" },
            { "Missing on this computer: {0}", "Absentes de cet ordinateur : {0}" },
            { "User Start", "Démarrage de l'utilisateur" },
            { "Create Group", "Créer un groupe" },
            { "Name the group", "Nommer le groupe" },
            { "Rename group", "Renommer le groupe" },
            { "Delete group", "Supprimer le groupe" },
            { "Group size: auto", "Taille du groupe : auto" },
            { "Fix width...", "Fixer la largeur..." },
            { "Fix width and height...", "Fixer la largeur et la hauteur..." },
            { "Width in cells", "Largeur en cellules" },
            { "Size as WxH, e.g. 8x3", "Taille en LxH, ex. 8x3" },
            { "Now: auto ({0}x{1})", "Actuel : auto ({0}x{1})" },
            { "Now: width {0} fixed, height auto", "Actuel : largeur {0} fixée, hauteur auto" },
            { "Now: width {0} and height {1} fixed", "Actuel : largeur {0} et hauteur {1} fixées" },
            { "Past search limit:", "Limite de recherche passée :" },
            { "Maximum number of past-search entries shown above results", "Nombre maximum d'entrées de recherches passées" },
            { "Regular search limit:", "Limite de recherche régulière :" },
            { "Maximum number of regular search results shown", "Nombre maximum de résultats de recherche réguliers" }
        };
    }
}