using System;
using System.Collections.Generic;

namespace WinPanel
{
    // Italian UI table for Loc: keys are the exact English source strings.
    public static class LangIt
    {
        public static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { " and more...", " e altro..." },
            { " at (", " a (" },
            { " items?", " elementi?" },
            { "\". Use Ctrl/Alt/Shift/Win + a letter or digit, e.g. Ctrl+Alt+P (or None).", "\". Formato: Ctrl/Alt/Shift/Win + lettera o cifra, es. Ctrl+Alt+P (oppure None)." },
            { "(empty)", "(vuoto)" },
            { "(no other tabs)", "(nessun'altra scheda)" },
            { "+ Save", "+ Salva" },
            { "Add Tab", "Aggiungi scheda" },
            { "Add bookmark group", "Aggiungi gruppo di segnalibri" },
            { "Add command", "Aggiungi comando" },
            { "Add command...", "Aggiungi comando..." },
            { "Add current folder", "Aggiungi cartella corrente" },
            { "Add current folder to bookmarks", "Aggiungi la cartella corrente ai segnalibri" },
            { "Add folder bookmark", "Aggiungi segnalibro cartella" },
            { "Add group...", "Aggiungi gruppo..." },
            { "Add to bookmarks", "Aggiungi ai segnalibri" },
            { "Add type...", "Aggiungi tipo..." },
            { "After autostart - go to tray", "Dopo l'avvio automatico - nell'area di notifica" },
            { "All", "Tutto" },
            { "Allow adding icons", "Consenti aggiunta di icone" },
            { "Always keep tray icon", "Mantieni sempre l'icona nell'area di notifica" },
            { "An error occurred but Tilettes keeps running.", "Si è verificato un errore ma Tilettes continua a funzionare." },
            { "Apps (system)", "App (sistema)" },
            { "Autostart & tray", "Avvio automatico e area di notifica" },
            { "Autostart with Windows", "Avvia con Windows" },
            { "BOOKMARKS", "SEGNALIBRI" },
            { "Backup created:", "Backup creato:" },
            { "Backup every N days (0 = off):", "Backup ogni N giorni (0 = off):" },
            { "Backup failed - see log.txt", "Backup non riuscito - vedi log.txt" },
            { "Backup now", "Backup adesso" },
            { "Backup saved: ", "Backup salvato: " },
            { "Bookmark name:", "Nome segnalibro:" },
            { "Bookmarks", "Segnalibri" },
            { "Calculator", "Calcolatrice" },
            { "Cancel", "Annulla" },
            { "Cannot parse the hotkey \"", "Impossibile interpretare la combinazione \"" },
            { "Cannot read the archive: ", "Impossibile leggere l'archivio: " },
            { "Capture the Win key", "Cattura il tasto Win" },
            { "Capture Start button click", "Cattura il clic sul pulsante Start" },
            { "Open tiles:", "Apri i tile:" },
            { "Open results:", "Apri i risultati:" },
            { "Single click", "Clic singolo" },
            { "Double click", "Doppio clic" },
            { "How tiles open: a single click launches right away, a double click needs two clicks", "Come si aprono i tile: un clic singolo apre subito, il doppio clic ne richiede due" },
            { "How search results open: by a single click or a double click", "Come si aprono i risultati della ricerca: con clic singolo o doppio clic" },
            { "A left click on the Start button (screen corner) opens the panel instead of the Start menu", "Un clic sinistro sul pulsante Start (angolo dello schermo) apre il pannello invece del menu Start" },
            { "Open Start menu", "Apri il menu Start" },
            { "Window", "Finestra" },
            { "Tile labels", "Etichette dei tile" },
            { "Folders", "Cartelle" },
            { "Panel & hotkeys", "Pannello e scorciatoie" },
            { "Fonts", "Caratteri" },
            { "File types & explorer", "Tipi di file ed esploratore" },
            { "Open folders with:", "Apri le cartelle con:" },
            { "Change Icon", "Cambia icona" },
            { "Change...", "Modifica..." },
            { "Check every N days:", "Controlla ogni N giorni:" },
            { "Check for updates automatically", "Cerca aggiornamenti automaticamente" },
            { "Check now", "Controlla adesso" },
            { "Clear", "Pulisci" },
            { "Clear history", "Cancella cronologia" },
            { "Clear selection", "Annulla selezione" },
            { "Click an address to copy it", "Clic su un indirizzo per copiarlo" },
            { "Click to copy the address", "Clic per copiare l'indirizzo" },
            { "Close", "Chiudi" },
            { "Close & create example tiles", "Chiudi e crea tessere d'esempio" },
            { "Command:", "Comando:" },
            { "Console", "Console" },
            { "Copied ✓", "Copiato ✓" },
            { "Copy folder path", "Copia percorso cartella" },
            { "Copy path", "Copia percorso" },
            { "Could not reach GitHub Releases - check the internet connection.", "Impossibile raggiungere GitHub Releases - controlla la connessione Internet." },
            { "Ctrl+Click a folder opens Mini Explorer", "Ctrl+clic su una cartella apre il mini esploratore" },
            { "Ctrl+L or Edit - edit path · F5 - refresh · Backspace - up · Enter - open · double-click - open", "Ctrl+L o Modifica - modifica percorso · F5 - aggiorna · Backspace - su · Invio - apri · doppio clic - apri" },
            { "Ctrl+mouse wheel - console font size", "Ctrl+rotella - dimensione carattere console" },
            { "Current window: ", "Finestra corrente: " },
            { "D", "D" },
            { "Def. Item Size:", "Dim. predef. tessere:" },
            { "Desc", "Descr" },
            { "Description", "Descrizione" },
            { "Description text", "Testo descrizione" },
            { "Description...", "Descrizione..." },
            { "Descriptions", "Descrizioni" },
            { "Details in log.txt", "Dettagli in log.txt" },
            { "Drag to resize the console", "Trascina per ridimensionare la console" },
            { "Edit", "Modifica" },
            { "Edit command", "Modifica comando" },
            { "Edit command...", "Modifica comando..." },
            { "Exact", "Esatto" },
            { "Exit", "Esci" },
            { "Expects a .zip created by \"Backup now\" / scheduled backup; files are unpacked into the working folder, Tilettes.exe is not replaced", "Attende un .zip creato da \"Backup adesso\" / backup pianificato; i file vengono estratti nella cartella di lavoro, Tilettes.exe non viene sostituito" },
            { "Explorer", "Esplora risorse" },
            { "Export...", "Esporta..." },
            { "Extract failed: ", "Estrazione non riuscita: " },
            { "Extract here (tar)", "Estrai qui (tar)" },
            { "File Type Icons", "Icone per tipo di file" },
            { "File manager", "Gestore file" },
            { "File types:", "Tipi di file:" },
            { "Folder", "Cartella" },
            { "Found a bug or have an idea? Create an issue on GitHub:", "Trovato un bug o hai un'idea? Apri una issue su GitHub:" },
            { "Full backup (settings + shortcuts + bookmarks) into autoBackup\\; runs 3 minutes after launch when due", "Backup completo (impostazioni + scorciatoie + segnalibri) in autoBackup\\; viene eseguito 3 minuti dopo l'avvio quando scade" },
            { "Fuzzy accuracy (0-3):", "Precisione fuzzy (0-3):" },
            { "Grid Columns:", "Colonne griglia:" },
            { "Grid Rows:", "Righe griglia:" },
            { "Grid Transp. (0-255):", "Transp. griglia (0-255):" },
            { "Grid:", "Griglia:" },
            { "Group (empty = top level):", "Gruppo (vuoto = primo livello):" },
            { "Group name:", "Nome gruppo:" },
            { "Icon Scale (%):", "Scala icone (%):" },
            { "Icons by type...", "Icone per tipo..." },
            { "Import...", "Importa..." },
            { "Install updates automatically", "Installa aggiornamenti automaticamente" },
            { "Just drag a shortcut or a file onto the panel - it becomes a tile.", "Trascina semplicemente un collegamento o un file sul pannello - diventa una tessera." },
            { "Language:", "Lingua:" },
            { "Light", "Chiaro" },
            { "Light Theme", "Tema chiaro" },
            { "Like Tilettes? Support the author with crypto:", "Ti piace Tilettes? Sostieni l'autore in crypto:" },
            { "M", "M" },
            { "Maintenance & Start Menu", "Manutenzione e Menu Start" },
            { "Match precision: exact or fuzzy (0-3)", "Precisione corrispondenza: esatta o fuzzy (0-3)" },
            { "Meta", "Meta" },
            { "Metadata", "Metadati" },
            { "Minimize instead of close", "Riduci a icona invece di chiudere" },
            { "More", "Altro" },
            { "Move down", "Sposta giù" },
            { "Move out of folder", "Estrai dalla cartella" },
            { "Move to tab", "Sposta sulla scheda" },
            { "Move up", "Sposta su" },
            { "New Name", "Nuovo nome" },
            { "New Tab Name", "Nome della nuova scheda" },
            { "New name:", "Nuovo nome:" },
            { "New version available: ", "Nuova versione disponibile: " },
            { "New version available: v", "Nuova versione disponibile: v" },
            { "New window", "Nuova finestra" },
            { "None (dark)", "Nessuna (scuro)" },
            { "Notepad", "Blocco note" },
            { "Nothing was restored - see log.txt", "Nulla è stato ripristinato - vedi log.txt" },
            { "OK", "OK" },
            { "Open", "Apri" },
            { "Open With by File Type", "Apri con per tipo di file" },
            { "Open console window here", "Apri qui la finestra console" },
            { "Open containing folder", "Apri cartella contenitore" },
            { "Open folders in:", "Apri le cartelle in:" },
            { "Open in Explorer", "Apri in Esplora risorse" },
            { "Open in Mini Explorer", "Apri nel mini esploratore" },
            { "Open standard", "Apri (standard)" },
            { "Open the donate section on GitHub", "Apri la sezione donazioni su GitHub" },
            { "Open with by type...", "Apri con per tipo..." },
            { "Paths", "Percorsi" },
            { "Popup window", "Finestra popup" },
            { "Pressing the Win key opens the panel instead of the Start menu", "Il tasto Win apre il pannello invece del menu Start" },
            { "Refresh", "Aggiorna" },
            { "Remember active tab", "Ricorda la scheda attiva" },
            { "Remove", "Rimuovi" },
            { "Remove ", "Rimuovi " },
            { "Remove from Panel", "Rimuovi dal pannello" },
            { "Remove icon", "Rimuovi icona" },
            { "Remove selected", "Rimuovi selezione" },
            { "Remove selected (", "Rimuovi selezione (" },
            { "Rename", "Rinomina" },
            { "Rename bookmark", "Rinomina segnalibro" },
            { "Rename...", "Rinomina..." },
            { "Restart", "Riavvia" },
            { "Restore", "Mostra" },
            { "Restore archive...", "Ripristina archivio..." },
            { "Restore backup", "Ripristina backup" },
            { "Restore failed: ", "Ripristino non riuscito: " },
            { "Restore from a backup archive", "Ripristina da un archivio di backup" },
            { "Return from a folder after this many seconds without activity (0 = off)", "Esce da una cartella dopo tanti secondi senza attività (0 = off)" },
            { "Run", "Esegui" },
            { "Same window", "Stessa finestra" },
            { "Save", "Salva" },
            { "Save backup", "Salva backup" },
            { "Save backup (zip)", "Salva backup (zip)" },
            { "Save failed: ", "Salvataggio non riuscito: " },
            { "Save search history", "Salva cronologia di ricerca" },
            { "Search", "Cerca" },
            { "Search files (fuzzy, any keyboard layout)", "Cerca file (fuzzy, qualsiasi layout di tastiera)" },
            { "Search fonts:", "Caratteri ricerca:" },
            { "Search history cleared.", "Cronologia di ricerca cancellata." },
            { "Search in descriptions", "Cerca nelle descrizioni" },
            { "Search in exe name, product, company", "Cerca nel nome exe, prodotto, società" },
            { "Search in full paths", "Cerca nei percorsi completi" },
            { "Search in item descriptions", "Cerca nelle descrizioni degli elementi" },
            { "Search in metadata (exe, product)", "Cerca nei metadati (exe, prodotto)" },
            { "Search in the Start Menu tab", "Cerca nella scheda Menu Start" },
            { "Search scope: click switches folder / everywhere", "Ambito ricerca: un clic passa cartella / ovunque" },
            { "Search...", "Cerca..." },
            { "Settings", "Impostazioni" },
            { "Show / hide bookmarks panel", "Mostra / nascondi pannello segnalibri" },
            { "Show / hide top bookmarks bar", "Mostra / nascondi barra segnalibri superiore" },
            { "Show in Explorer", "Mostra in Esplora risorse" },
            { "Show the welcome window again", "Mostra di nuovo la finestra di benvenuto" },
            { "Show window hotkey:", "Scorciatoia mostra finestra:" },
            { "Simple text editor", "Semplice editor di testo" },
            { "Size", "Dimensione" },
            { "Size-1", "1 x 1" },
            { "Skin & theme:", "Skin e tema:" },
            { "Start", "Start" },
            { "Start Menu", "Menu Start" },
            { "Start Menu (all users)", "Menu Start (tutti gli utenti)" },
            { "Start Menu (local)", "Menu Start (locale)" },
            { "Start Menu (user)", "Menu Start (utente)" },
            { "Start Menu sync failed - see log.txt", "Sincronizzazione Menu Start non riuscita - vedi log.txt" },
            { "Start Menu synced:", "Menu Start sincronizzato:" },
            { "Startup Size:", "Dimensione all'avvio:" },
            { "Support section on GitHub (README)", "Sezione di supporto su GitHub (README)" },
            { "Support the author", "Sostieni l'autore" },
            { "Sync Start Menu every N h (0 = off):", "Sinc. Menu Start ogni N ore (0 = off):" },
            { "Sync Start Menu now", "Sincronizza Menu Start adesso" },
            { "Tabs Font:", "Carattere schede:" },
            { "Thanks for trying Tilettes!", "Grazie per aver provato Tilettes!" },
            { "The app periodically asks GitHub Releases for a newer version (no auto-download yet)", "L'app chiede periodicamente a GitHub Releases se esiste una versione più recente (nessun download automatico per ora)" },
            { "The description is used by the search and pops up as a tooltip when hovering the element.", "La descrizione è usata dalla ricerca e appare come tooltip passando sopra l'elemento." },
            { "This archive has no settings.ini / records.xml - it is not a Tilettes backup.", "Questo archivio non contiene settings.ini / records.xml - non è un backup di Tilettes." },
            { "This is a beta version - bugs and rough edges are possible.", "Questa è una versione beta - bug e imperfezioni sono possibili." },
            { "Tiles Font:", "Carattere tessere:" },
            { "Tilettes", "Tilettes" },
            { "Tilettes backup archives (*.zip)|*.zip|All files (*.*)|*.*", "Archivi di backup Tilettes (*.zip)|*.zip|Tutti i file (*.*)|*.*" },
            { "Tilettes console · ", "Console Tilettes · " },
            { "Tilettes rules (*.xml)|*.xml|All files (*.*)|*.*", "Regole Tilettes (*.xml)|*.xml|Tutti i file (*.*)|*.*" },
            { "UI Font:", "Carattere interfaccia:" },
            { "Update", "Aggiorna" },
            { "Updates", "Aggiornamenti" },
            { "Version ", "Versione " },
            { "Wallet addresses and other ways to help live on GitHub:", "Gli indirizzi dei wallet e gli altri modi per aiutare sono su GitHub:" },
            { "Window Position:", "Posizione finestra:" },
            { "Windows calculator", "Calcolatrice di Windows" },
            { "You are on the latest version: v", "Hai l'ultima versione: v" },
            { "[console process exited - press Restart]", "[processo console terminato - premi Riavvia]" },
            { "\nThe green Update plate has appeared in the corner.", "\nLa targhetta verde Aggiorna è apparsa nell'angolo." },
            { "address copied to clipboard", "indirizzo copiato negli appunti" },
            { "box", "campo" },
            { "columns x", "colonne x" },
            { "results", "risultati" },
            { "rows", "righe" },
            { "sec idle", "s di inattività" },
            { "text", "testo" },
            { "♥ Donate", "♥ Dona" },

            // Tab menus / prompts (previously hard-coded English)
            { "Create Folder", "Crea cartella" },
            { "Folder Name", "Nome cartella" },
            { "Delete Tab", "Elimina scheda" },
            { "Rename Tab", "Rinomina scheda" },
            { "Toggle Layout (Free / Grid)", "Cambia layout (libero / griglia)" },
            { "Are you sure you want to delete this tab?", "Eliminare davvero questa scheda?" },
            { "Cannot remove the last tab.", "Impossibile rimuovere l'ultima scheda." },
            { "Empty", "Vuoto" },
            { "Mini Explorer", "Mini esploratore" },
            { "Rebuild icons & paths", "Ricostruisci icone e percorsi" },
            { "Checked: {0} · missing paths: {1} · cache files removed: {2}",
              "Verificati: {0} · percorsi mancanti: {1} · file di cache rimossi: {2}" },
            { "Tile label: two rows", "Etichetta tile: due righe" },
            { "2 rows align:", "Allinea 2 righe:" },
            { "Left", "Sinistra" },
            { "Center", "Centro" },
            { "Right", "Destra" },
            { "Hide shortcut suffix ( - Shortcut)", "Nascondi suffisso collegamento ( - Collegamento)" },
            { "Hide file extension (.mp4)", "Nascondi estensione file (.mp4)" },
            { "Extra rows below:", "Righe extra sotto:" },
            { "Extra tile rows under the visible grid, same cell size; scroll down to reach them (0 = off)",
              "Righe di piastrelle extra sotto la griglia visibile, stessa dimensione; raggiungibili scorrendo in basso (0 = off)" },
            { "Past search", "Ricerche recenti" },
            { "Command (%1 = current folder):", "Comando (%1 = cartella corrente):" },
            { "in bookmarks %1 = current folder", "nei segnalibri %1 = cartella corrente" }
        };
    }
}
