using System;
using System.Collections.Generic;

namespace WinPanel
{
    // German UI table for Loc: keys are the exact English source strings.
    public static class LangDe
    {
        public static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { " and more...", " und mehr..." },
            { " at (", " bei (" },
            { " items?", " Elemente?" },
            { "\". Use Ctrl/Alt/Shift/Win + a letter or digit, e.g. Ctrl+Alt+P (or None).", "\". Format: Ctrl/Alt/Shift/Win + Buchstabe oder Ziffer, z. B. Ctrl+Alt+P (oder None)." },
            { "(empty)", "(leer)" },
            { "(no other tabs)", "(keine anderen Tabs)" },
            { "+ Save", "+ Speichern" },
            { "Add Tab", "Tab hinzufügen" },
            { "Add bookmark group", "Lesezeichen-Gruppe hinzufügen" },
            { "Add command", "Befehl hinzufügen" },
            { "Add command...", "Befehl hinzufügen..." },
            { "Add current folder", "Aktuellen Ordner hinzufügen" },
            { "Add current folder to bookmarks", "Aktuellen Ordner zu Lesezeichen hinzufügen" },
            { "Add folder bookmark", "Ordner-Lesezeichen hinzufügen" },
            { "Add group...", "Gruppe hinzufügen..." },
            { "Add to bookmarks", "Zu Lesezeichen hinzufügen" },
            { "Add type...", "Typ hinzufügen..." },
            { "After autostart - go to tray", "Nach Autostart - in den Tray" },
            { "All", "Alle" },
            { "Allow adding icons", "Hinzufügen von Symbolen erlauben" },
            { "Always keep tray icon", "Tray-Symbol immer anzeigen" },
            { "An error occurred but Tilettes keeps running.", "Ein Fehler ist aufgetreten, aber Tilettes läuft weiter." },
            { "Apps (system)", "Apps (System)" },
            { "Autostart & tray", "Autostart & Tray" },
            { "Autostart with Windows", "Mit Windows autostarten" },
            { "BOOKMARKS", "LESEZEICHEN" },
            { "Backup created:", "Backup erstellt:" },
            { "Backup every N days (0 = off):", "Backup alle N Tage (0 = aus):" },
            { "Backup failed - see log.txt", "Backup fehlgeschlagen - siehe log.txt" },
            { "Backup now", "Backup jetzt" },
            { "Backup saved: ", "Backup gespeichert: " },
            { "Bookmark name:", "Lesezeichenname:" },
            { "Bookmarks", "Lesezeichen" },
            { "Calculator", "Rechner" },
            { "Cancel", "Abbrechen" },
            { "Cannot parse the hotkey \"", "Tastenkombination nicht erkennbar: \"" },
            { "Cannot read the archive: ", "Archiv kann nicht gelesen werden: " },
            { "Capture the Win key", "Win-Taste abfangen" },
            { "Capture Start button click", "Klick auf die Start-Taste abfangen" },
            { "A left click on the Start button (screen corner) opens the panel instead of the Start menu", "Ein Linksklick auf die Start-Taste (Bildschirmecke) öffnet das Panel statt des Startmenüs" },
            { "Open Start menu", "Startmenü öffnen" },
            { "Window", "Fenster" },
            { "Tile labels", "Kachelbeschriftungen" },
            { "Folders", "Ordner" },
            { "Panel & hotkeys", "Panel & Hotkeys" },
            { "Fonts", "Schriftarten" },
            { "File types & explorer", "Dateitypen & Explorer" },
            { "Open folders with:", "Ordner öffnen mit:" },
            { "Change Icon", "Symbol ändern" },
            { "Change...", "Ändern..." },
            { "Check every N days:", "Alle N Tage prüfen:" },
            { "Check for updates automatically", "Automatisch nach Updates suchen" },
            { "Check now", "Jetzt prüfen" },
            { "Clear", "Leeren" },
            { "Clear history", "Verlauf löschen" },
            { "Clear selection", "Auswahl aufheben" },
            { "Click an address to copy it", "Klick auf eine Adresse kopiert sie" },
            { "Click to copy the address", "Klicken, um die Adresse zu kopieren" },
            { "Close", "Schließen" },
            { "Close & create example tiles", "Schließen & Beispielskacheln erstellen" },
            { "Command:", "Befehl:" },
            { "Console", "Konsole" },
            { "Copied ✓", "Kopiert ✓" },
            { "Copy folder path", "Ordnerpfad kopieren" },
            { "Copy path", "Pfad kopieren" },
            { "Could not reach GitHub Releases - check the internet connection.", "GitHub Releases nicht erreichbar - Internetverbindung prüfen." },
            { "Ctrl+Click a folder opens Mini Explorer", "Ctrl+Klick auf einen Ordner öffnet den Mini-Explorer" },
            { "Ctrl+L or Edit - edit path · F5 - refresh · Backspace - up · Enter - open · double-click - open", "Ctrl+L oder Bearbeiten - Pfad bearbeiten · F5 - aktualisieren · Backspace - höher · Enter - öffnen · Doppelklick - öffnen" },
            { "Ctrl+mouse wheel - console font size", "Ctrl+Mausrad - Konsolenschriftgröße" },
            { "Current window: ", "Aktuelles Fenster: " },
            { "D", "B" },
            { "Def. Item Size:", "Std. Kachelgröße:" },
            { "Desc", "Beschr" },
            { "Description", "Beschreibung" },
            { "Description text", "Beschreibungstext" },
            { "Description...", "Beschreibung..." },
            { "Descriptions", "Beschreibungen" },
            { "Details in log.txt", "Details in log.txt" },
            { "Drag to resize the console", "Ziehen, um die Konsolengröße zu ändern" },
            { "Edit", "Bearbeiten" },
            { "Edit command", "Befehl bearbeiten" },
            { "Edit command...", "Befehl bearbeiten..." },
            { "Exact", "Exakt" },
            { "Exit", "Beenden" },
            { "Expects a .zip created by \"Backup now\" / scheduled backup; files are unpacked into the working folder, Tilettes.exe is not replaced", "Erwartet ein .zip aus \"Backup jetzt\" / geplantem Backup; Dateien werden in den Arbeitsordner entpackt, Tilettes.exe wird nicht ersetzt" },
            { "Explorer", "Explorer" },
            { "Export...", "Exportieren..." },
            { "Extract failed: ", "Entpacken fehlgeschlagen: " },
            { "Extract here (tar)", "Hier entpacken (tar)" },
            { "File Type Icons", "Symbole nach Dateityp" },
            { "File manager", "Dateimanager" },
            { "File types:", "Dateitypen:" },
            { "Folder", "Ordner" },
            { "Found a bug or have an idea? Create an issue on GitHub:", "Fehler gefunden oder eine Idee? Erstelle ein Issue auf GitHub:" },
            { "Full backup (settings + shortcuts + bookmarks) into autoBackup\\; runs 3 minutes after launch when due", "Vollbackup (Einstellungen + Verknüpfungen + Lesezeichen) in autoBackup\\; läuft 3 Minuten nach dem Start, wenn fällig" },
            { "Fuzzy accuracy (0-3):", "Fuzzy-Genauigkeit (0-3):" },
            { "Grid Columns:", "Grid-Spalten:" },
            { "Grid Rows:", "Grid-Zeilen:" },
            { "Grid Transp. (0-255):", "Grid-Transp. (0-255):" },
            { "Grid:", "Raster:" },
            { "Group (empty = top level):", "Gruppe (leer = oberste Ebene):" },
            { "Group name:", "Gruppenname:" },
            { "Icon Scale (%):", "Symbolgröße (%):" },
            { "Icons by type...", "Symbole nach Typ..." },
            { "Import...", "Importieren..." },
            { "Install updates automatically", "Updates automatisch installieren" },
            { "Just drag a shortcut or a file onto the panel - it becomes a tile.", "Einfach eine Verknüpfung oder Datei auf das Panel ziehen - daraus wird eine Kachel." },
            { "Language:", "Sprache:" },
            { "Light", "Hell" },
            { "Light Theme", "Helles Design" },
            { "Like Tilettes? Support the author with crypto:", "Tilettes nützlich? Unterstütze den Autor mit Krypto:" },
            { "M", "M" },
            { "Maintenance & Start Menu", "Wartung & Startmenü" },
            { "Match precision: exact or fuzzy (0-3)", "Übereinstimmungsgenauigkeit: exakt oder fuzzy (0-3)" },
            { "Meta", "Meta" },
            { "Metadata", "Metadaten" },
            { "Minimize instead of close", "Minimieren statt schließen" },
            { "More", "Mehr" },
            { "Move down", "Nach unten" },
            { "Move out of folder", "Aus Ordner herausziehen" },
            { "Move to tab", "Auf Tab verschieben" },
            { "Move up", "Nach oben" },
            { "New Name", "Neuer Name" },
            { "New Tab Name", "Name des neuen Tabs" },
            { "New name:", "Neuer Name:" },
            { "New version available: ", "Neue Version verfügbar: " },
            { "New version available: v", "Neue Version verfügbar: v" },
            { "New window", "Neues Fenster" },
            { "None (dark)", "Ohne (dunkel)" },
            { "Notepad", "Editor" },
            { "Nothing was restored - see log.txt", "Nichts wiederhergestellt - siehe log.txt" },
            { "OK", "OK" },
            { "Open", "Öffnen" },
            { "Open With by File Type", "Öffnen mit nach Dateityp" },
            { "Open console window here", "Konsolenfenster hier öffnen" },
            { "Open containing folder", "Übergeordneten Ordner öffnen" },
            { "Open folders in:", "Ordner öffnen in:" },
            { "Open in Explorer", "Im Explorer öffnen" },
            { "Open in Mini Explorer", "Im Mini-Explorer öffnen" },
            { "Open standard", "Öffnen (Standard)" },
            { "Open the donate section on GitHub", "Spendenbereich auf GitHub öffnen" },
            { "Open with by type...", "Öffnen mit nach Typ..." },
            { "Paths", "Pfade" },
            { "Popup window", "Popup-Fenster" },
            { "Pressing the Win key opens the panel instead of the Start menu", "Die Win-Taste öffnet das Panel statt des Startmenüs" },
            { "Refresh", "Aktualisieren" },
            { "Remember active tab", "Aktiven Tab merken" },
            { "Remove", "Entfernen" },
            { "Remove ", "Entfernen " },
            { "Remove from Panel", "Vom Panel entfernen" },
            { "Remove icon", "Symbol entfernen" },
            { "Remove selected", "Auswahl entfernen" },
            { "Remove selected (", "Auswahl entfernen (" },
            { "Rename", "Umbenennen" },
            { "Rename bookmark", "Lesezeichen umbenennen" },
            { "Rename...", "Umbenennen..." },
            { "Restart", "Neustart" },
            { "Restore", "Anzeigen" },
            { "Restore archive...", "Archiv wiederherstellen..." },
            { "Restore backup", "Backup wiederherstellen" },
            { "Restore failed: ", "Wiederherstellung fehlgeschlagen: " },
            { "Restore from a backup archive", "Aus einem Backup-Archiv wiederherstellen" },
            { "Return from a folder after this many seconds without activity (0 = off)", "Nach so vielen Sekunden ohne Aktivität aus einem Ordner zurück (0 = aus)" },
            { "Run", "Ausführen" },
            { "Same window", "Gleiches Fenster" },
            { "Save", "Speichern" },
            { "Save backup", "Backup speichern" },
            { "Save backup (zip)", "Backup speichern (zip)" },
            { "Save failed: ", "Speichern fehlgeschlagen: " },
            { "Save search history", "Suchverlauf speichern" },
            { "Search", "Suchen" },
            { "Search files (fuzzy, any keyboard layout)", "Dateien suchen (fuzzy, jedes Tastaturlayout)" },
            { "Search fonts:", "Suchschriftarten:" },
            { "Search history cleared.", "Suchverlauf gelöscht." },
            { "Search in descriptions", "In Beschreibungen suchen" },
            { "Search in exe name, product, company", "In Exe-Name, Produkt, Firma suchen" },
            { "Search in full paths", "In vollen Pfaden suchen" },
            { "Search in item descriptions", "In Elementbeschreibungen suchen" },
            { "Search in metadata (exe, product)", "In Metadaten suchen (exe, Produkt)" },
            { "Search in the Start Menu tab", "Im Startmenü-Tab suchen" },
            { "Search scope: click switches folder / everywhere", "Suchbereich: Klick schaltet Ordner / überall" },
            { "Search...", "Suchen..." },
            { "Settings", "Einstellungen" },
            { "Show / hide bookmarks panel", "Lesezeichenleiste zeigen / verbergen" },
            { "Show / hide top bookmarks bar", "Obere Lesezeichenleiste zeigen / verbergen" },
            { "Show in Explorer", "Im Explorer anzeigen" },
            { "Show the welcome window again", "Willkommensfenster erneut zeigen" },
            { "Show window hotkey:", "Hotkey Fenster zeigen:" },
            { "Simple text editor", "Einfacher Texteditor" },
            { "Size", "Größe" },
            { "Size-1", "1 x 1" },
            { "Skin & theme:", "Skin & Design:" },
            { "Start", "Start" },
            { "Start Menu", "Startmenü" },
            { "Start Menu (all users)", "Startmenü (alle Benutzer)" },
            { "Start Menu (local)", "Startmenü (lokal)" },
            { "Start Menu (user)", "Startmenü (Benutzer)" },
            { "Start Menu sync failed - see log.txt", "Startmenü-Sync fehlgeschlagen - siehe log.txt" },
            { "Start Menu synced:", "Startmenü synchronisiert:" },
            { "Startup Size:", "Startgröße:" },
            { "Support section on GitHub (README)", "Unterstützungsbereich auf GitHub (README)" },
            { "Support the author", "Autor unterstützen" },
            { "Sync Start Menu every N h (0 = off):", "Startmenü alle N Std. synchr. (0 = aus):" },
            { "Sync Start Menu now", "Startmenü jetzt synchronisieren" },
            { "Tabs Font:", "Tabs-Schrift:" },
            { "Thanks for trying Tilettes!", "Danke, dass du Tilettes ausprobierst!" },
            { "The app periodically asks GitHub Releases for a newer version (no auto-download yet)", "Die App fragt GitHub Releases periodisch nach einer neueren Version (noch kein automatischer Download)" },
            { "The description is used by the search and pops up as a tooltip when hovering the element.", "Die Beschreibung wird von der Suche genutzt und erscheint als Tooltip beim Überfahren des Elements." },
            { "This archive has no settings.ini / records.xml - it is not a Tilettes backup.", "Dieses Archiv enthält kein settings.ini / records.xml - es ist kein Tilettes-Backup." },
            { "This is a beta version - bugs and rough edges are possible.", "Dies ist eine Beta-Version - Fehler und unausgereifte Stellen sind möglich." },
            { "Tiles Font:", "Kacheln-Schrift:" },
            { "Tilettes", "Tilettes" },
            { "Tilettes backup archives (*.zip)|*.zip|All files (*.*)|*.*", "Tilettes-Backup-Archive (*.zip)|*.zip|Alle Dateien (*.*)|*.*" },
            { "Tilettes console · ", "Tilettes-Konsole · " },
            { "Tilettes rules (*.xml)|*.xml|All files (*.*)|*.*", "Tilettes-Regeln (*.xml)|*.xml|Alle Dateien (*.*)|*.*" },
            { "UI Font:", "UI-Schrift:" },
            { "Update", "Update" },
            { "Updates", "Updates" },
            { "Version ", "Version " },
            { "Wallet addresses and other ways to help live on GitHub:", "Wallet-Adressen und andere Unterstützungsmöglichkeiten gibt es auf GitHub:" },
            { "Window Position:", "Fensterposition:" },
            { "Windows calculator", "Windows-Rechner" },
            { "You are on the latest version: v", "Du bist auf der neuesten Version: v" },
            { "[console process exited - press Restart]", "[Konsolenprozess beendet - Neustart drücken]" },
            { "\nThe green Update plate has appeared in the corner.", "\nDie grüne Update-Plakette ist in der Ecke erschienen." },
            { "address copied to clipboard", "Adresse in die Zwischenablage kopiert" },
            { "box", "Eingabefeld" },
            { "columns x", "Spalten x" },
            { "results", "Ergebnisse" },
            { "rows", "Zeilen" },
            { "sec idle", "Sek. Leerlauf" },
            { "text", "Text" },
            { "♥ Donate", "♥ Spenden" },

            // Tab menus / prompts (previously hard-coded English)
            { "Create Folder", "Ordner erstellen" },
            { "Folder Name", "Ordnername" },
            { "Delete Tab", "Tab löschen" },
            { "Rename Tab", "Tab umbenennen" },
            { "Toggle Layout (Free / Grid)", "Layout umschalten (frei / Raster)" },
            { "Are you sure you want to delete this tab?", "Diesen Tab wirklich löschen?" },
            { "Cannot remove the last tab.", "Der letzte Tab kann nicht entfernt werden." },
            { "Empty", "Leer" },
            { "Mini Explorer", "Mini-Explorer" },
            { "Rebuild icons & paths", "Symbole & Pfade neu einlesen" },
            { "Checked: {0} · missing paths: {1} · cache files removed: {2}",
              "Geprüft: {0} · fehlende Pfade: {1} · Cachedateien gelöscht: {2}" },
            { "Tile label: two rows", "Kachelbeschriftung: zwei Zeilen" },
            { "2 rows align:", "2 Zeilen ausrichten:" },
            { "Left", "Links" },
            { "Center", "Mitte" },
            { "Right", "Rechts" },
            { "Hide shortcut suffix ( - Shortcut)", "Verknüpfungssuffix ausblenden ( - Verknüpfung)" },
            { "Hide file extension (.mp4)", "Dateierweiterung ausblenden (.mp4)" }
        };
    }
}
