using System;
using System.Collections.Generic;

namespace WinPanel
{
    // Polish UI table for Loc: keys are the exact English source strings.
    public static class LangPl
    {
        public static readonly Dictionary<string, string> Table = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { " and more...", " i więcej..." },
            { " at (", " w (" },
            { " items?", " elementów?" },
            { "\". Use Ctrl/Alt/Shift/Win + a letter or digit, e.g. Ctrl+Alt+P (or None).", "\". Format: Ctrl/Alt/Shift/Win + litera lub cyfra, np. Ctrl+Alt+P (lub None)." },
            { "(empty)", "(puste)" },
            { "(no other tabs)", "(brak innych kart)" },
            { "+ Save", "+ Zapisz" },
            { "Add Tab", "Dodaj kartę" },
            { "Add bookmark group", "Dodaj grupę zakładek" },
            { "Add command", "Dodaj polecenie" },
            { "Add command...", "Dodaj polecenie..." },
            { "Add current folder", "Dodaj bieżący folder" },
            { "Add current folder to bookmarks", "Dodaj bieżący folder do zakładek" },
            { "Add folder bookmark", "Dodaj zakładkę folderu" },
            { "Add group...", "Dodaj grupę..." },
            { "Add to bookmarks", "Dodaj do zakładek" },
            { "Add type...", "Dodaj typ..." },
            { "After autostart - go to tray", "Po autostarcie - do zasobnika" },
            { "All", "Wszędzie" },
            { "Allow adding icons", "Zezwalaj na dodawanie ikon" },
            { "Always keep tray icon", "Zawsze pokazuj ikonę w zasobniku" },
            { "An error occurred but Tilettes keeps running.", "Wystąpił błąd, ale Tilettes dalej działa." },
            { "Apps (system)", "Aplikacje (systemowe)" },
            { "Autostart & tray", "Autostart i zasobnik" },
            { "Autostart with Windows", "Uruchamiaj z Windows" },
            { "BOOKMARKS", "ZAKŁADKI" },
            { "Backup created:", "Utworzono kopię zapasową:" },
            { "Backup every N days (0 = off):", "Kopia co N dni (0 = wył.):" },
            { "Backup failed - see log.txt", "Kopia zapasowa nie powiodła się - zobacz log.txt" },
            { "Backup now", "Kopia teraz" },
            { "Backup saved: ", "Zapisano kopię: " },
            { "Bookmark name:", "Nazwa zakładki:" },
            { "Bookmarks", "Zakładki" },
            { "Calculator", "Kalkulator" },
            { "Cancel", "Anuluj" },
            { "Cannot parse the hotkey \"", "Nie można odczytać skrótu \"" },
            { "Cannot read the archive: ", "Nie można odczytać archiwum: " },
            { "Capture the Win key", "Przechwytuj klawisz Win" },
            { "Capture Start button click", "Przechwytuj kliknięcie przycisku Start" },
            { "Open tiles:", "Otwieranie kafelków:" },
            { "Open results:", "Otwieranie wyników:" },
            { "Single click", "Pojedyncze kliknięcie" },
            { "Double click", "Podwójne kliknięcie" },
            { "How tiles open: a single click launches right away, a double click needs two clicks", "Jak otwierać kafelki: pojedyncze kliknięcie otwiera od razu, podwójne wymaga dwóch" },
            { "How search results open: by a single click or a double click", "Jak otwierać wyniki wyszukiwania: pojedynczym lub podwójnym kliknięciem" },
            { "A left click on the Start button (screen corner) opens the panel instead of the Start menu", "Lewy klik na przycisku Start (róg ekranu) otwiera panel zamiast menu Start" },
            { "Open Start menu", "Otwórz menu Start" },
            { "Window", "Okno" },
            { "Tile labels", "Podpisy kafelków" },
            { "Folders", "Foldery" },
            { "Panel & hotkeys", "Panel i skróty" },
            { "Fonts", "Czcionki" },
            { "File types & explorer", "Typy plików i eksplorator" },
            { "Open folders with:", "Otwieraj foldery przez:" },
            { "Change Icon", "Zmień ikonę" },
            { "Change...", "Zmień..." },
            { "Check every N days:", "Sprawdzaj co N dni:" },
            { "Check for updates automatically", "Automatycznie sprawdzaj aktualizacje" },
            { "Check now", "Sprawdź teraz" },
            { "Clear", "Wyczyść" },
            { "Clear history", "Wyczyść historię" },
            { "Clear selection", "Wyczyść zaznaczenie" },
            { "Click an address to copy it", "Kliknij adres, aby go skopiować" },
            { "Click to copy the address", "Kliknij, aby skopiować adres" },
            { "Close", "Zamknij" },
            { "Close & create example tiles", "Zamknij i utwórz przykładowe kafelki" },
            { "Command:", "Polecenie:" },
            { "Console", "Konsola" },
            { "Copied ✓", "Skopiowano ✓" },
            { "Copy folder path", "Kopiuj ścieżkę folderu" },
            { "Copy path", "Kopiuj ścieżkę" },
            { "Could not reach GitHub Releases - check the internet connection.", "Nie można połączyć się z GitHub Releases - sprawdź internet." },
            { "Ctrl+Click a folder opens Mini Explorer", "Ctrl+klik na folderze otwiera mini eksplorator" },
            { "Ctrl+L or Edit - edit path · F5 - refresh · Backspace - up · Enter - open · double-click - open", "Ctrl+L lub Edytuj - edycja ścieżki · F5 - odśwież · Backspace - wyżej · Enter - otwórz · dwuklik - otwórz" },
            { "Ctrl+mouse wheel - console font size", "Ctrl+kółko - rozmiar czcionki konsoli" },
            { "Current window: ", "Bieżące okno: " },
            { "D", "O" },
            { "Def. Item Size:", "Domyślny rozmiar:" },
            { "Desc", "Opisy" },
            { "Description", "Opis" },
            { "Description text", "Treść opisu" },
            { "Description...", "Opis..." },
            { "Descriptions", "Opisy" },
            { "Details in log.txt", "Szczegóły w log.txt" },
            { "Drag to resize the console", "Przeciągnij, aby zmienić wysokość konsoli" },
            { "Edit", "Edytuj" },
            { "Edit command", "Edytuj polecenie" },
            { "Edit command...", "Edytuj polecenie..." },
            { "Exact", "Dokładne" },
            { "Exit", "Zakończ" },
            { "Expects a .zip created by \"Backup now\" / scheduled backup; files are unpacked into the working folder, Tilettes.exe is not replaced", "Oczekuje .zip utworzonego przez \"Kopia teraz\" / kopię zaplanowaną; pliki są rozpakowywane do folderu roboczego, Tilettes.exe nie jest zastępowany" },
            { "Explorer", "Eksplorator" },
            { "Export...", "Eksportuj..." },
            { "Extract failed: ", "Rozpakowanie nie powiodło się: " },
            { "Extract here (tar)", "Rozpakuj tutaj (tar)" },
            { "File Type Icons", "Ikony według typu pliku" },
            { "File manager", "Menedżer plików" },
            { "File types:", "Typy plików:" },
            { "Folder", "Folder" },
            { "Found a bug or have an idea? Create an issue on GitHub:", "Znalazłeś błąd lub masz pomysł? Utwórz issue na GitHub:" },
            { "Full backup (settings + shortcuts + bookmarks) into autoBackup\\; runs 3 minutes after launch when due", "Pełna kopia (ustawienia + skróty + zakładki) do autoBackup\\; uruchamiana 3 minuty po starcie, gdy przyszedł termin" },
            { "Fuzzy accuracy (0-3):", "Dokładność fuzzy (0-3):" },
            { "Grid Columns:", "Kolumny siatki:" },
            { "Grid Rows:", "Wiersze siatki:" },
            { "Grid Transp. (0-255):", "Przezr. siatki (0-255):" },
            { "Grid:", "Siatka:" },
            { "Group (empty = top level):", "Grupa (puste = najwyższy poziom):" },
            { "Group name:", "Nazwa grupy:" },
            { "Icon Scale (%):", "Skala ikon (%):" },
            { "Icons by type...", "Ikony wg typu..." },
            { "Import...", "Importuj..." },
            { "Install updates automatically", "Instaluj aktualizacje automatycznie" },
            { "Just drag a shortcut or a file onto the panel - it becomes a tile.", "Po prostu przeciągnij skrót lub plik na panel - powstanie kafelek." },
            { "Language:", "Język:" },
            { "Light", "Jasny" },
            { "Light Theme", "Jasny motyw" },
            { "Like Tilettes? Support the author with crypto:", "Podoba ci się Tilettes? Wesprzyj autora kryptowalutami:" },
            { "M", "M" },
            { "Maintenance & Start Menu", "Serwis i Menu Start" },
            { "Match precision: exact or fuzzy (0-3)", "Dokładność dopasowania: dokładne lub rozmyte (0-3)" },
            { "Meta", "Meta" },
            { "Metadata", "Metadane" },
            { "Minimize instead of close", "Minimalizuj zamiast zamykać" },
            { "More", "Więcej" },
            { "Move down", "W dół" },
            { "Move out of folder", "Wyjmij z folderu" },
            { "Move to tab", "Przenieś na kartę" },
            { "Move up", "W górę" },
            { "New Name", "Nowa nazwa" },
            { "New Tab Name", "Nazwa nowej karty" },
            { "New name:", "Nowa nazwa:" },
            { "New version available: ", "Dostępna nowa wersja: " },
            { "New version available: v", "Dostępna nowa wersja: v" },
            { "New window", "Nowe okno" },
            { "None (dark)", "Brak (ciemny)" },
            { "Notepad", "Notatnik" },
            { "Nothing was restored - see log.txt", "Nic nie przywrócono - zobacz log.txt" },
            { "OK", "OK" },
            { "Open", "Otwórz" },
            { "Open With by File Type", "Otwieranie wg typu pliku" },
            { "Open console window here", "Otwórz tutaj okno konsoli" },
            { "Open containing folder", "Otwórz folder nadrzędny" },
            { "Open folders in:", "Otwieraj foldery w:" },
            { "Open in Explorer", "Otwórz w Eksploratorze" },
            { "Open in Mini Explorer", "Otwórz w mini eksploratorze" },
            { "Open standard", "Otwórz (standardowo)" },
            { "Open the donate section on GitHub", "Otwórz sekcję wsparcia na GitHub" },
            { "Open with by type...", "Otwieranie wg typu..." },
            { "Paths", "Ścieżki" },
            { "Popup window", "Okno wyskakujące" },
            { "Pressing the Win key opens the panel instead of the Start menu", "Klawisz Win otwiera panel zamiast menu Start" },
            { "Refresh", "Odśwież" },
            { "Remember active tab", "Pamiętaj aktywną kartę" },
            { "Remove", "Usuń" },
            { "Remove ", "Usuń " },
            { "Remove from Panel", "Usuń z panelu" },
            { "Remove icon", "Usuń ikonę" },
            { "Remove selected", "Usuń zaznaczone" },
            { "Remove selected (", "Usuń zaznaczone (" },
            { "Rename", "Zmień nazwę" },
            { "Rename bookmark", "Zmień nazwę zakładki" },
            { "Rename...", "Zmień nazwę..." },
            { "Restart", "Restart" },
            { "Restore", "Pokaż" },
            { "Restore archive...", "Przywróć z archiwum..." },
            { "Restore backup", "Przywróć kopię" },
            { "Restore failed: ", "Przywracanie nie powiodło się: " },
            { "Restore from a backup archive", "Przywracanie z archiwum kopii zapasowej" },
            { "Return from a folder after this many seconds without activity (0 = off)", "Wyjście z folderu po tylu sekundach bezczynności (0 = wył.)" },
            { "Run", "Uruchom" },
            { "Same window", "To samo okno" },
            { "Save", "Zapisz" },
            { "Save backup", "Zapisz kopię" },
            { "Save backup (zip)", "Zapisz kopię (zip)" },
            { "Save failed: ", "Zapis nie powiódł się: " },
            { "Save search history", "Zapisuj historię wyszukiwania" },
            { "Search", "Szukaj" },
            { "Search files (fuzzy, any keyboard layout)", "Szukaj plików (rozmyte, dowolny układ klawiatury)" },
            { "Search fonts:", "Czcionki wyszukiwania:" },
            { "Search history cleared.", "Historia wyszukiwania wyczyszczona." },
            { "Search in descriptions", "Szukaj w opisach" },
            { "Search in exe name, product, company", "Szukaj w nazwie exe, produkcie, firmie" },
            { "Search in full paths", "Szukaj w pełnych ścieżkach" },
            { "Search in item descriptions", "Szukaj w opisach elementów" },
            { "Search in metadata (exe, product)", "Szukaj w metadanych (exe, produkt)" },
            { "Search in the Start Menu tab", "Szukaj w karcie Menu Start" },
            { "Search scope: click switches folder / everywhere", "Zakres: klik przełącza folder / wszędzie" },
            { "Search...", "Szukaj..." },
            { "Settings", "Ustawienia" },
            { "Show / hide bookmarks panel", "Pokaż / ukryj panel zakładek" },
            { "Show / hide top bookmarks bar", "Pokaż / ukryj górny pasek zakładek" },
            { "Show in Explorer", "Pokaż w Eksploratorze" },
            { "Show the welcome window again", "Pokaż ponownie okno powitalne" },
            { "Show window hotkey:", "Skrót pokazania okna:" },
            { "Simple text editor", "Prosty edytor tekstu" },
            { "Size", "Rozmiar" },
            { "Size-1", "1 x 1" },
            { "Skin & theme:", "Skórka i motyw:" },
            { "Start", "Start" },
            { "Start Menu", "Menu Start" },
            { "Start Menu (all users)", "Menu Start (wszyscy użytkownicy)" },
            { "Start Menu (local)", "Menu Start (lokalne)" },
            { "Start Menu (user)", "Menu Start (użytkownika)" },
            { "Start Menu sync failed - see log.txt", "Synchronizacja Menu Start nie powiodła się - zobacz log.txt" },
            { "Start Menu synced:", "Zsynchronizowano Menu Start:" },
            { "Startup Size:", "Rozmiar przy starcie:" },
            { "Support section on GitHub (README)", "Sekcja wsparcia na GitHub (README)" },
            { "Support the author", "Wesprzyj autora" },
            { "Sync Start Menu every N h (0 = off):", "Synchronizuj Menu Start co N godz. (0 = wył.):" },
            { "Sync Start Menu now", "Synchronizuj Menu Start teraz" },
            { "Tabs Font:", "Czcionka kart:" },
            { "Thanks for trying Tilettes!", "Dziękujemy, że wypróbowujesz Tilettes!" },
            { "The app periodically asks GitHub Releases for a newer version (no auto-download yet)", "Aplikacja okresowo pyta GitHub Releases o nowszą wersję (na razie bez automatycznego pobierania)" },
            { "The description is used by the search and pops up as a tooltip when hovering the element.", "Opis jest używany przez wyszukiwanie i pojawia się jako podpowiedź przy najechaniu na element." },
            { "This archive has no settings.ini / records.xml - it is not a Tilettes backup.", "To archiwum nie zawiera settings.ini / records.xml - to nie jest kopia Tilettes." },
            { "This is a beta version - bugs and rough edges are possible.", "To wersja beta - możliwe błędy i niedopracowania." },
            { "Tiles Font:", "Czcionka kafelków:" },
            { "Tilettes", "Tilettes" },
            { "Tilettes backup archives (*.zip)|*.zip|All files (*.*)|*.*", "Archiwa kopii Tilettes (*.zip)|*.zip|Wszystkie pliki (*.*)|*.*" },
            { "Tilettes console · ", "Konsola Tilettes · " },
            { "Tilettes rules (*.xml)|*.xml|All files (*.*)|*.*", "Reguły Tilettes (*.xml)|*.xml|Wszystkie pliki (*.*)|*.*" },
            { "UI Font:", "Czcionka interfejsu:" },
            { "Update", "Aktualizuj" },
            { "Updates", "Aktualizacje" },
            { "Version ", "Wersja " },
            { "Wallet addresses and other ways to help live on GitHub:", "Adresy portfeli i inne sposoby wsparcia są na GitHub:" },
            { "Window Position:", "Pozycja okna:" },
            { "Windows calculator", "Kalkulator Windows" },
            { "You are on the latest version: v", "Masz najnowszą wersję: v" },
            { "[console process exited - press Restart]", "[proces konsoli zakończony - naciśnij Restart]" },
            { "\nThe green Update plate has appeared in the corner.", "\nZielony przycisk Aktualizuj pojawił się w rogu." },
            { "address copied to clipboard", "adres skopiowany do schowka" },
            { "box", "pole" },
            { "columns x", "kolumn x" },
            { "results", "wyniki" },
            { "rows", "wierszy" },
            { "sec idle", "s bezczynności" },
            { "text", "tekst" },
            { "♥ Donate", "♥ Wsparcie" },

            // Tab menus / prompts (previously hard-coded English)
            { "Create Folder", "Utwórz folder" },
            { "Folder Name", "Nazwa folderu" },
            { "Delete Tab", "Usuń kartę" },
            { "Rename Tab", "Zmień nazwę karty" },
            { "Toggle Layout (Free / Grid)", "Przełącz układ (swobodny / siatka)" },
            { "Are you sure you want to delete this tab?", "Czy na pewno usunąć tę kartę?" },
            { "Cannot remove the last tab.", "Nie można usunąć ostatniej karty." },
            { "Empty", "Pusto" },
            { "Mini Explorer", "Mini-eksplorator" },
            { "Rebuild icons & paths", "Przebuduj ikony i ścieżki" },
            { "Checked: {0} · missing paths: {1} · cache files removed: {2}",
              "Sprawdzono: {0} · brakujące ścieżki: {1} · usunięte pliki cache: {2}" },
            { "Tile label: two rows", "Podpis kafelka: dwa wiersze" },
            { "2 rows align:", "Wyrównanie 2 wierszy:" },
            { "Left", "Lewo" },
            { "Center", "Środek" },
            { "Right", "Prawo" },
            { "Hide shortcut suffix ( - Shortcut)", "Ukryj sufiks skrótu ( - Skrót)" },
            { "Hide file extension (.mp4)", "Ukryj rozszerzenie pliku (.mp4)" },
            { "Extra rows below:", "Dodatkowe rzędy na dole:" },
            { "Extra tile rows under the visible grid, same cell size; scroll down to reach them (0 = off)",
              "Dodatkowe rzędy kafelków pod widoczną siatką, ten sam rozmiar; dostępne po przewinięciu w dół (0 = wył.)" }
        };
    }
}
